apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-sonarr-config-pv
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/sonarr/config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: media
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: local-sonarr-config-pv
