apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
      version: "4.0.0"
  values:
    nfs:
      server: openmediavault.home.dcxxiv.com
      path: /export/Media
