apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: weave-gitops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:h1m+O+s+gJQcfhdulPJj8L1eD4KMT0bMbTZIFtw2dEmeEkwTxxH5Q8c=,iv:qXYdJ31FetdlEmp9phRM4SjSY4EePFysXG/jmYysBxY=,tag:jyghD57yGanghKXPjmlmfA==,type:comment]
    #ENC[AES256_GCM,data:nI7QnhmXTVhCIE/b0gG73DFWm7lBC7ynNZfa0M2ZRFL2ndkQdX3Qo71W3Q==,iv:KexUOeiepGFN43K5snyOtN48AYJGNGETWU3XUNHTDvw=,tag:5aa4Swko2Fh3FJ9YeNLjmg==,type:comment]
    #ENC[AES256_GCM,data:ZueIK8J9Dy+/9P/tYEgD0W5YvSbQhj26R17a++y/s+WiLZwX+tB3ErHQXxFN3ZvqTxYXiLoOGP1i0ZSUAefTgw==,iv:O+CtKndPD49XRDIizIH2aLpnPou3pXt4bI+sKtFUvjQ=,tag:TWDMTjwgR46yqmQF9KQPBA==,type:comment]
    #ENC[AES256_GCM,data:yqeKletavknykLGDqVJQJs1wd2L7XVhumPK8Q1zR+O5j4nnIx2D3IQckSv0=,iv:J/M2S9/eH8K0i3sHE6nLpM5w3rVeLiEPEtqrwGdnnos=,tag:r2kVXqVRXW1xNC/gaUdDiw==,type:comment]
    password: ENC[AES256_GCM,data:jOLq5GKWxwcrbgPuRNVrwb0eLxd9izaT4Nel7mBB/zxQSIM4aw==,iv:LZTnJORWVCeoS8m4vpgBTpi1jS8u5qLdGtUmy0HhvbQ=,tag:zZ820sawPEoae9TFYln90Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR3lvTEtUaDBSMHF1VGUy
            TEhOeDN1amxwcXdQS0d0OW1WSTFYeFpnb1FnCm9rd0MybkdIKzYxemxIOFA1NHRF
            cDlKU256NGFSUUNxQzV1NlZRUEpmVkUKLS0tIHV1dyt4RXdKZDE0cDBVc3ZrUFR1
            T1pwK0ZkK3R2VEpRN2lQNkdQS2IyVmcKGfKHk8cdMlmJp/0OhSX9oo+99wOpg6xl
            zXUVPGE8KN6kl3J4WHNplJbBelvgat/NcpT8gGTnMjlNiTNNJU2mdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T20:50:51Z"
    mac: ENC[AES256_GCM,data:gh7UIZSH4UTHpWPQkNcmFwMkXY6/4GSHvaeriGCnASnxmZak2cVNyP7c2KAzO7zChraYvMeTXdJgajm+43ott5SCl4tLkfX4o+p6V170AN55YGWYoaT13Ezn91l8Y7vaTAgGCLFWxnBALrE2r0KEZYrbHELMFL++9VG/FaALgSw=,iv:ngus4uyMZf94S56nelBzsnpWegACA2V4h2Y79vjm8BI=,tag:mQAbec6l64kp4UZnbVTisg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: oidc-auth
    namespace: weave-gitops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:eAEFw8s2fdLhGDN2+hPfWpVT9HKAUFBcnuCpYlm3TUQVVaFd9AIOZLVRTSlBM/gbkFUC8ESk1ewWhQmx5ViTqhYGVw9Rg29riF3ejofnsAmW0Jiv,iv:7Op/iR+7pIQ5EZYL9S8HfojzHl9/jl3nWLCyZPSRHJA=,tag:3abvAqk34V1nCEKKy9hkIw==,type:comment]
    #ENC[AES256_GCM,data:Jui2OJhhNRcJeMIfYLSeDIky4tjjGHeYQf3QGwbq1241fO1mZoomgQ+eS7BA6i75HGZ5N7TyZbHZyhEnh3XC9lx6tMCgYqP6j6/rK8KOZA==,iv:CMCplBS8f6WrDdQn53K2n8ZYn69aAY46/5aY3UCXIDk=,tag:nsUbQa7LaDj8aqD1iGN7aA==,type:comment]
    clientID: ENC[AES256_GCM,data:bWPrNFfhoEftoAlO,iv:poegDtzlVsYkYY9+q+IqJejzubpoA3VZ+CxLlwq060s=,tag:cCtVkITCTPOv1RVC43ooNw==,type:str]
    clientSecret: ENC[AES256_GCM,data:pYFKmYWlOyBfFcRjOGBb4OiTiQZbrIeZrF7tL6WkYzQDHsXDxDEoPuG5y3Sp+ctA1So2+H/6X/Gm2aFitaegiA==,iv:FQk2VyXWtqXZbE27m+6fedWRHsULP3EoLquYCJeoC5g=,tag:JwF3ygsSdn+Zal32JCEIMg==,type:str]
    issuerURL: ENC[AES256_GCM,data:m3UkKTzn83HoYHqGVCqulNzhGckYnqa2QYiOl7g8gRt50yicrztw2O4yHGn5omCYvHHA,iv:/VOds1EftWA95ff6W1boet8uRwcgJxejHA2uIdXuRJI=,tag:7BcS9b3Wk/Ga9xeZhuxucw==,type:str]
    redirectURL: ENC[AES256_GCM,data:4TEXlomEpmV/UsSkm6Ji0d05wSRHjYibUy2FDDDfDdaX7daTtmkB,iv:N6gzgp5SOn9IjeUrjN2U2YVeFtS7kPhVawrWr6HAZDE=,tag:PQqQ1akBEBmL6iVG8STdjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR3lvTEtUaDBSMHF1VGUy
            TEhOeDN1amxwcXdQS0d0OW1WSTFYeFpnb1FnCm9rd0MybkdIKzYxemxIOFA1NHRF
            cDlKU256NGFSUUNxQzV1NlZRUEpmVkUKLS0tIHV1dyt4RXdKZDE0cDBVc3ZrUFR1
            T1pwK0ZkK3R2VEpRN2lQNkdQS2IyVmcKGfKHk8cdMlmJp/0OhSX9oo+99wOpg6xl
            zXUVPGE8KN6kl3J4WHNplJbBelvgat/NcpT8gGTnMjlNiTNNJU2mdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T20:50:51Z"
    mac: ENC[AES256_GCM,data:gh7UIZSH4UTHpWPQkNcmFwMkXY6/4GSHvaeriGCnASnxmZak2cVNyP7c2KAzO7zChraYvMeTXdJgajm+43ott5SCl4tLkfX4o+p6V170AN55YGWYoaT13Ezn91l8Y7vaTAgGCLFWxnBALrE2r0KEZYrbHELMFL++9VG/FaALgSw=,iv:ngus4uyMZf94S56nelBzsnpWegACA2V4h2Y79vjm8BI=,tag:mQAbec6l64kp4UZnbVTisg==,type:str]
    version: 3.13.1
