apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: weave-gitops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:kAOTFmPODbLWp3QyAVwDMtansO0A9I4bv3Da0sKAGlw7PUCdyO1irbc=,iv:ACz3qmXyCgckWPqdVieFhYeu228C2igvwi9qdxbk/9g=,tag:xrbOReb1ZKsKX81Apq46tg==,type:comment]
    #ENC[AES256_GCM,data:DidxZiwVZbH8xMOXyRJnSU4Lv2Oht5LZ0vCoAEMwUDSn8y9/87/paunHHw==,iv:Bk6OGCk4C+hD307PVdlqO7jUEDMrVcq49jV/ebB+Puw=,tag:dDha4b5mrz/pYHrGhAW+kA==,type:comment]
    #ENC[AES256_GCM,data:W0R/V0e58zzK01HseoRKxXjHmiUaHGiLBOC7Jwv3rzwtgEC5nv7QSMPow/rEb3NbEAgL0n5ndJHXiy3Bdac+Qw==,iv:jsW+fzbCWK8kQrbAPosgikrRbGO1Uu8ZdNq9TiNH8T0=,tag:8xSVo5hBzZqINx4f2VbpuQ==,type:comment]
    #ENC[AES256_GCM,data:nLf8slrWUwT37JKKLrDEOPnN3l7sI4p26u0GmiaPygcvYRCAY6FCQf6uutw=,iv:8sjX4QtTfMCs4wSrsCFI2i9o++zhZz853jA1NJuWzRk=,tag:KZ+xvAZ3Seq8tl/dGf33iQ==,type:comment]
    password: ENC[AES256_GCM,data:T07/4qVVLUDGzgfNN4GyC/cxyox+tqO7OStXsJeQAVQRnhwJAg==,iv:ehaINY0mtI+/3UfP2dA7KCS3q9Iyg5uy0I0pbMB+p2Q=,tag:khv9ER51BhlImdHjTgafMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvalhNYUJMajFXYUR6QkZK
            eUVucFQvbDBEOHpYR1pBWUczRkoyZjRPWTFBCkVScFBEMzFaRVZMY1ZNbHd5NUsv
            ZkFla1Q0RUFwV2xRQ29sOWgyOXNEeEUKLS0tIG0wNThJYXRGUXI1YWI3Nk5CYVdI
            ZUhDSGUzZ1U0bVlWME43eDhvREp6MmsKI2Jso7aP3io/0EXmU4JF40sxrkqy6zmj
            FRtjCX3sVP/a1GFaqhsmftkPxdoA04kxkJ75bon0xOtaelpgZusPWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T21:30:41Z"
    mac: ENC[AES256_GCM,data:VaWhiPqvfheIcWmyYDNNPZMJ7AJC8DKCKg/ZHkS/UESSs+IKonVEd9ZzW2Ne+TAWH8BzTT6HojQsOBpPc6Oh1PnNGZu/+KQJTpf1nkI6fNGuacDH/fR7kdxeZBEBKvM1H5j42mKA50YXs5LNYTYLiT4cBl4qngX8or+1SgjTqMY=,iv:avTYi1hrxMjvxfIvU0cQ+t76TEacRslcA1FPJhGJr7Y=,tag:UJu5T5Nm4XJUAPG76NFIoQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: oidc-auth
    namespace: weave-gitops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Z5nhOxG8zujWxHOnX3Bth51y0p1mFUQdkvz5bpAMTTpGZF7pqVFL8SNK+Su+DoQagtpwB38208QVZkrzl5R4tzSs2lnw47Xv/90TD9xqHUJgi7x8,iv:zhU4TYKniN0T4HDkhcFc2gBxQk/7cbVO3mGQIkCCYoc=,tag:Icpcp/Q7p+EDr4PQQAXUXQ==,type:comment]
    #ENC[AES256_GCM,data:PRE62jutgE6dqwrj0TosvkUa5mExziUPT3iUSbVWFx7oYV7El41mfwYv9dSXp9w/umC5CHvuRuJBePkMvxCkdslXXF8IFomF1oP/qkEnyg==,iv:01F1CGEHG3Q1tbEdt8iZ+ct0plauJ98KQNAYMpaAIdY=,tag:+9Bf4hKqzPcDkjqDFv+WPw==,type:comment]
    clientID: ENC[AES256_GCM,data:hh4CcZ21SdxS8/mp,iv:KFoIMV7ZWTCpoO5/kS7yl1yZtSUoAJk5L1yYtdySOdg=,tag:q/alfa1LqVgh0s/K8lHe6Q==,type:str]
    clientSecret: ENC[AES256_GCM,data:qR5T7nte6sCQdIO7zhPc5yi2SeRROxEBulIcQ45PXphWOhF7bq81WFCTo/Pw0DUTsHdYAoJzoO2sCL0oQkctAA==,iv:pZO1X+1GU0QRsxNLT5JPgY5/HiPHrjiHQJmjJRLdgr8=,tag:WI4yqxV1RZxt5PJ6qjrRMQ==,type:str]
    issuerURL: ENC[AES256_GCM,data:qknmVPqrtNy9zq9wvmPFfOJ7b/+ESDnHt0VzbZlAByVwI0G3qSuOMdoDsL78tOBqQ9L3,iv:zob5p/KizMCbjOEPn8XAK+6j8ygaxemkgiOETnjOuEY=,tag:I3xXrKdKyC6+aYLemNBNqA==,type:str]
    redirectURL: ENC[AES256_GCM,data:T14k8Kkj+wXnCmrNl2ZtHDiN40adpUA0dz2DixrRYPE76At3jRcl,iv:bySD4Og05e9NR+6mUwtJkG1UH2VjyeHOxEvcekUeiUc=,tag:C7FKMUTl/Skr6o/ODBqBJA==,type:str]
    customScopes: ENC[AES256_GCM,data:xazjbllvrJltBytsPSUNgmYz6q8cWn3VYn3q,iv:Qv60/eOO2jI4ROG1ocp9siumJn+WYuWq7gsbvd3mfWQ=,tag:hLhfxYBIpJCAhe3F9i2FIA==,type:str]
    claimGroups: ENC[AES256_GCM,data:AN31zEfI,iv:zMgi6zY2tHROrDFy6Un7xFKMc5xMoK8HavfHflgD9jI=,tag:rWCeKYoXB76F6Zp76olF1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvalhNYUJMajFXYUR6QkZK
            eUVucFQvbDBEOHpYR1pBWUczRkoyZjRPWTFBCkVScFBEMzFaRVZMY1ZNbHd5NUsv
            ZkFla1Q0RUFwV2xRQ29sOWgyOXNEeEUKLS0tIG0wNThJYXRGUXI1YWI3Nk5CYVdI
            ZUhDSGUzZ1U0bVlWME43eDhvREp6MmsKI2Jso7aP3io/0EXmU4JF40sxrkqy6zmj
            FRtjCX3sVP/a1GFaqhsmftkPxdoA04kxkJ75bon0xOtaelpgZusPWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T21:30:41Z"
    mac: ENC[AES256_GCM,data:VaWhiPqvfheIcWmyYDNNPZMJ7AJC8DKCKg/ZHkS/UESSs+IKonVEd9ZzW2Ne+TAWH8BzTT6HojQsOBpPc6Oh1PnNGZu/+KQJTpf1nkI6fNGuacDH/fR7kdxeZBEBKvM1H5j42mKA50YXs5LNYTYLiT4cBl4qngX8or+1SgjTqMY=,iv:avTYi1hrxMjvxfIvU0cQ+t76TEacRslcA1FPJhGJr7Y=,tag:UJu5T5Nm4XJUAPG76NFIoQ==,type:str]
    version: 3.13.1
