apiVersion: v1
kind: Secret
metadata:
    name: agent-os-env
    namespace: agent-os
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CSFyjfkhmmwYARuSZyla6ycI4N5Vb22o6gkJWkc4h0AF7Lr9c2MUztz+FL5bG6Ac1iIwFxTIvoClSqyCWcsN+YWNDNeEruCVSN3PmQ==,iv:iGjLhyDywmD4FHyJmY4iI+PUpDdH6A37bhYGgxVpboI=,tag:tekuvHhy7yEofciRwe2Tqg==,type:comment]
    #ENC[AES256_GCM,data:Mq3UogNHHuu9+f0TMqdavZxotbbKoC8YV+7uTAbCtBwwRLMZ7k78,iv:P4+xu6ABJEf2mt0C1e/kMmM5kVniOPedcIjQfJ7NUb8=,tag:5cgHK7Y/DdXkkQbqSKIwKA==,type:comment]
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:pGih+hI6meBtt/ntl6zmO885vjPviSLEszDbsRapUuS7x5cXMjBN+Ckd0re6QGwp0AWe7YY2K7apQ1Bml+eg2lXmS50env73WeCB4xUBqajlwA3k3+9QcCggL3YrnoyYv8aF+MIXmZzhrzrQ,iv:Kvm7V7/gsYelafxUe39z6WdAt6Udf0aoiLYDxc595Zc=,tag:eP1Bi9KJljK9LoTkNNnooA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQd3VYN3B3Y2dTM1NZL0tJ
            WGVBWlYzdG9DdXFiNXgwZkJ0bDZBYjlzTjA4CjBnTnNzbTlrV25BaU04TXY0QmlR
            VHAwcWUxbll6cVJLTW1UNWlndHVnTTQKLS0tIGt0NS9FQUVLNjBETTNkQkVoREJK
            bGhrRnlyajNCbUxaVnRzMW5lNnVCancKhi6chefBN2xfbCeWCLgN8ea7823iGv9l
            ONC6g9MMoJWQG2ZXdXfI3QQdNDAd44SV4pEmjNa+ZVq32e3I7HSumw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T16:44:19Z"
    mac: ENC[AES256_GCM,data:RUqlkjEl6UZ0+2pTFiewmxUMM4SYywgahuIK9DCbH21Ri8dZ2Pd7lDlH8Ml5yqFJRgk223ocIO4z6rJE8b8cSYMezhiRBqBhLBUpk8Uus6lix0LOUnGkAmZwhecXFqngtfhCgdI4a3SNgQrwhOYfY1RQcGttya3MXlXI/0AJi2I=,iv:IJrCbDGcnUS7xDySc4zVMdwwB4865MlvmLo93cj24C0=,tag:mDHn0iewTbgRzUYjwnrQdw==,type:str]
    version: 3.13.1
