apiVersion: v1
kind: Secret
metadata:
    name: agent-os-env
    namespace: agent-os
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CSFyjfkhmmwYARuSZyla6ycI4N5Vb22o6gkJWkc4h0AF7Lr9c2MUztz+FL5bG6Ac1iIwFxTIvoClSqyCWcsN+YWNDNeEruCVSN3PmQ==,iv:iGjLhyDywmD4FHyJmY4iI+PUpDdH6A37bhYGgxVpboI=,tag:tekuvHhy7yEofciRwe2Tqg==,type:comment]
    #ENC[AES256_GCM,data:Mq3UogNHHuu9+f0TMqdavZxotbbKoC8YV+7uTAbCtBwwRLMZ7k78,iv:P4+xu6ABJEf2mt0C1e/kMmM5kVniOPedcIjQfJ7NUb8=,tag:5cgHK7Y/DdXkkQbqSKIwKA==,type:comment]
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:zNfq2okvez1V9j+G9EicYV/uVvTS/w==,iv:AKW6Ao2uJXnieIOZJPbfH666TmGPiD03k5PBBaYHze0=,tag:DRH0LlpcrresCX2G/fHdvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQd3VYN3B3Y2dTM1NZL0tJ
            WGVBWlYzdG9DdXFiNXgwZkJ0bDZBYjlzTjA4CjBnTnNzbTlrV25BaU04TXY0QmlR
            VHAwcWUxbll6cVJLTW1UNWlndHVnTTQKLS0tIGt0NS9FQUVLNjBETTNkQkVoREJK
            bGhrRnlyajNCbUxaVnRzMW5lNnVCancKhi6chefBN2xfbCeWCLgN8ea7823iGv9l
            ONC6g9MMoJWQG2ZXdXfI3QQdNDAd44SV4pEmjNa+ZVq32e3I7HSumw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T16:04:22Z"
    mac: ENC[AES256_GCM,data:p7qw6aQoYIFe8F1txm/5m2IXAaCaZKBC+77VFvyEMOw5PusL7De9740PuPtsEzk7q2Lq6MY5Pqz/nosve7qT01oLfRurGc2d/9MOVE0OX0yErMlqIn452Ie3QmBokKPKk0deN+we/vsO2QxmyAALMmfPO5mv6yXEZmeOfjb4A2o=,iv:J/L9t90hLbIOt3jPFJyev7A6empt+LKgu6YDizo+vGY=,tag:ILjaPb2demAh8JrCURCAzw==,type:str]
    version: 3.13.1
