apiVersion: v1
kind: Secret
metadata:
    name: personliness-secret
    namespace: personliness
type: Opaque
stringData:
    #ENC[AES256_GCM,data:z4dAdkaKLg+em0OnWWjSWJUcrITXGXc0zFfaWZ5ihe0SZ/F0e6J9Td3KK9/3Q3YROS+AK8ApaIiNA+QNrqDp633v,iv:gPVn8M7gXFtOJDwp2SApKz0vLmiPqapiD7ZEJi0YUic=,tag:zk6IwLuFQRvuw7EXJRNKGQ==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XP0ZutNPzPipIG7wR03S4UtZPbQOSle5zZRaNcYdYtIidRuu8Gle2fUu7Q==,iv:LYBBFVBFgxaxZFFPzzPEHodhlNaudvQGMSKelb++Uy0=,tag:MF4bsLIP/wgdmJg8cqxJUQ==,type:str]
    #ENC[AES256_GCM,data:nlNm5SYGkAwczCybXuqO9LzY,iv:afmXGBSrMhuZmm744TSGOqSLPzlOjVjSt9s/wiZ81aw=,tag:BBqIaz5gs2kwWTy1Se/03Q==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:RLcoXt4DnJqDonY6H7A5d6L9VwcTfkaOsQR3nLbGd+xFxR8niYXsmX3clA==,iv:mYdcD0RwAVmnFmWcNsX7pMeT7wPZpxxS3OajkZAP/6w=,tag:6BMQjrtxxuF86CkFvsGIYg==,type:str]
    #ENC[AES256_GCM,data:3IK2fM3Sr8IrPec+BQO9g5RJBMk4zahiJwzfBINGT7SS2YLu1Tbw6rx98IoCB7SP5as7bWXC37uI2mYI,iv:xcjGkvrsNcycIxFeosAu88PdlKUme982kayo7iEZp80=,tag:YBODopnC+aWQ9gsuVyD6Zg==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Qk5wdXFpWlMxV3Y4RTFO
            QWlqMEE5c0lBNWR1aDNqVmh4ZnNJdVNaaFFJCk1kWmlxNWJneFRKSm53UEkvRkNw
            UXpZWXF6WXdpVUhDeHFDeEdMMGRCbUkKLS0tIDM0TUY1WDQrQ0hqVUlab21lWlNL
            b0lpelZTa0M2M3NtU2ZHclRONTV3NG8KaNA29rvCRqPrlvPyaZ3tHM0wZDRJiqyF
            pz1Z0mzFzU7t6KQbxa+KfBlWRCcX5jliwfNU4OQZX2DwWgFiqdtIVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T23:34:32Z"
    mac: ENC[AES256_GCM,data:SmymhcScJpH7+VPuzxt03WrfUhYCHDmaCZx64tg/TqQWtbXAuuY9XsGyQZ/2f3N5cvQ6+Anw3Jh+jKcfyNwNN9WotcRGkatrJZPUsTucsjpGAIuzsKZKmoV5r8bzrBLvMPvztDVhRORMlerg2CEGRzhjRL7nAb498liUTHUqF9Q=,iv:HrXUhib8JHDk3pfJDfJhDwSEDQhixZu4XVCQWaTZLuo=,tag:xgKaBwvUoZ7vUqYCELukDA==,type:str]
    version: 3.13.1
