apiVersion: v1
kind: Secret
metadata:
    name: personliness-secret
    namespace: personliness
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:aUUsq+A23fzkvQ5ssoBZId5WBtipgqHftfixriaKJ9M=,iv:VG2qf3CY0FyxIy2uxF0braQml2Ge35zK9WKD5PBv07c=,tag:lIaWJO+kYV8a0w2cRqXLQw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:/G/SjXRW/ze4j1/PocKTisLkfivgELp9dUCsdPVfsuTtcpVp+eVzu6+7kplGNxR721YVcFZFoXoluMBBz75GDA==,iv:WYz1ZCWue6NB9rWUiU/Ft/2N/dZV1WTZre3rErbjC+M=,tag:uD+qskhFJZIqGZu34SRjIg==,type:str]
    LLM_ANTHROPIC_API_KEY: ENC[AES256_GCM,data:w/tHnC0r+jKBVBTpafWMQA3upFa02avORR4X+1qY2fWQEt7C8kfTBdCk6ogkN8jLY/c2bBWNYKBsCnTxjssN8aoKRYibmIYRxDEtwhWMTYVBS6N8CGFWfW8/kNLuYpDvO5f/AlOZbwc3kq5B,iv:ZerKE/CwbQKPBw1dU4ZlAS84rLc0LjD6SAyfGX94ymE=,tag:fJxQr+frMMau0RHP31nCoQ==,type:str]
    DJANGO_SUPERUSER_USERNAME: ENC[AES256_GCM,data:gvfVMAU=,iv:c7COTRpZYtmk4aVMaaqmhTUw5Gef0gV58m+eCu1m44A=,tag:iE+RfsvrW59rfPvBUS6Bww==,type:str]
    DJANGO_SUPERUSER_EMAIL: ENC[AES256_GCM,data:QcYJ3mYxJYlSy0MxDjgKL9QNryu41cgGzsaqNtZpprs=,iv:Y+BS36xje3m5f8NKYvI2HR+hoIwCAjVI31yNiCdPBY4=,tag:qq0xtnT24XM43bBkhSChdA==,type:str]
    DJANGO_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:PDwzOMqaQV3xqLEZax0L3D+Z5nA=,iv:VcfFrLy6mQZQpolib0IVt0UCx00jPPpdd43kyrsXZQA=,tag:aY86nTU+zOaGgqMyR21EvA==,type:str]
    CELERY_BROKER_URL: ENC[AES256_GCM,data:DmqP0Yt1EHN/VBsYjLisHxkyJjKmHU4pCYmGdRf+GwM0UhOUNm7GhLQ2eOBxdE74MvGQf8mgqfKfer4icyGk1Re978Ey2C0cNJ6VLgfh7vmWI3l0s2ksOY/sS6C8O/IHLw==,iv:ErcY5TzUdj0uXD3F55/zdLxh3KmOVX+U9Zqg9qCnnQM=,tag:hTx01kuQD0kV+d8vB+xDHQ==,type:str]
    CELERY_RESULT_BACKEND: ENC[AES256_GCM,data:wSBUtQ4yp5ot5rMuWZ6LDvrfC3Kyxqz014+toEBxBaukyu+Wvk4yBu2tDjuVM+s5P+WoSaaZSNImq8iCVFbuxw/4SgRucoTqiBo3G0OJ77omNjbiGQ0k8SMvdiR0Nr+qFw==,iv:x53RI6indaTMnEBMNX81v659mN/3aplC2uiXKcBhIo8=,tag:o9SZKIEHTcRnM/ak1wlxLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM2dpOG45ckcxOHg4VC9z
            WnE3MEJqUHZKYWxPZUJac1pzdmkxdFVtSFVZCklNbDJQdW43a21maGNENmFkVGhK
            U2t6blU1RGNIN0JlZ2tyWUJUYXloNGsKLS0tIG5CdkRFd0RIVGtOM0hjcnRoaUgr
            NTBmcm92TWI3TGVmWXk0MTJCejkrWEUKM96SySnLk3lFBdbtRGgMAD4BiR9spA3j
            wYVDWWPHmDPFUUfaetUZBTRi4jRlETBUlKTlAxqn5oJI7sG0Hj3hmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:21:35Z"
    mac: ENC[AES256_GCM,data:Xir+anvvjwJnsCgcf6itnM9Z/mkj6RJ/FacknWxUzt06Q0fKOeRHOWv00zGuKA7il20tbkCEBAGcW5myleL+SnqRGOQFR7vIdOprNPBVryAtN/j7eGB1RQmTu5wJ1n+t6KfLheon7tKpiVJ2iYw1dOhg4NIbx9/MaIIkareGOuo=,iv:bXh6L+aqdGWXRfoJsZDAigSE6xVHQb8BH5KDOJu3+VA=,tag:jZKcMfeqY4+e+tcpo/oS2g==,type:str]
    version: 3.13.1
