apiVersion: v1
kind: Secret
metadata:
    name: personliness-secret
    namespace: personliness
type: Opaque
stringData:
    #ENC[AES256_GCM,data:z4dAdkaKLg+em0OnWWjSWJUcrITXGXc0zFfaWZ5ihe0SZ/F0e6J9Td3KK9/3Q3YROS+AK8ApaIiNA+QNrqDp633v,iv:gPVn8M7gXFtOJDwp2SApKz0vLmiPqapiD7ZEJi0YUic=,tag:zk6IwLuFQRvuw7EXJRNKGQ==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:W99vOqamNO1BgwvDErhckA+a6gk8NgPt0gTsfejJVw4=,iv:tVbFM3PHps/DnqVMCYmUm0EcRyXdbg6ssq4BRxzhquM=,tag:Lod21OIZhVT0Dg8QZQoawg==,type:str]
    #ENC[AES256_GCM,data:nlNm5SYGkAwczCybXuqO9LzY,iv:afmXGBSrMhuZmm744TSGOqSLPzlOjVjSt9s/wiZ81aw=,tag:BBqIaz5gs2kwWTy1Se/03Q==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:EUftvGeIrHP5Nyj+qLt0ewWbYqpDO5GOisIwkthHA1Pl4GhRPvc7SWbq3thzPwpBm/0rQTPysXgHnXvoqz/EDQ==,iv:6JkazoMt93obnG37e1AeHB9E58uUIP9SqODl55QWmFc=,tag:S5f7fzppXPLxEd03KtOACg==,type:str]
    #ENC[AES256_GCM,data:3IK2fM3Sr8IrPec+BQO9g5RJBMk4zahiJwzfBINGT7SS2YLu1Tbw6rx98IoCB7SP5as7bWXC37uI2mYI,iv:xcjGkvrsNcycIxFeosAu88PdlKUme982kayo7iEZp80=,tag:YBODopnC+aWQ9gsuVyD6Zg==,type:comment]
    LLM_ANTHROPIC_API_KEY: ENC[AES256_GCM,data:luarHI2KhidbRf0/E4ryqxsjrxLH8KYk7YwhNbTU7SzFEfyrfs0EIBbw4Ro77TcmPprTYGeF4WqOy/mykmQDMjBQL1Vb5SWTMwEF+Zwq1mhVA1BanMWCcAcb+T+n7FNYHAU/Wtu1wMdR0uyT,iv:S8awIQbcAVSZaKsMOOhepHFJ90Mt4mroLmBTPVBdYGU=,tag:DjgW5s+f7X+AyHVD85hg7A==,type:str]
    DJANGO_SUPERUSER_USERNAME: ENC[AES256_GCM,data:Ae/wQf8=,iv:l/sC/5ov3EXGc5BptQlyf9UvJBnlqZvmrlfEpPI9ufc=,tag:u2q5rlF/BZ6m1+qPT0Gg9A==,type:str]
    DJANGO_SUPERUSER_EMAIL: ENC[AES256_GCM,data:X7z5Xla27SyLhEJNnmxW35shKW8MWz69kvhIir+fw0g=,iv:SZ7MNL7fH7dyST9CgiKaLabzUuwfcC8zaVt/t2hWPng=,tag:YHxbehR1afYYuT0WVHf/yg==,type:str]
    DJANGO_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:sNdcrdSFHzgbHfWh13/cAxaEQt0=,iv:XpqixEvzDqFkrOuPqBlRtiA5QvbN/v2q+iE0H64hf8Q=,tag:FME3cJyY5Z3TqaDJI9ETXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Qk5wdXFpWlMxV3Y4RTFO
            QWlqMEE5c0lBNWR1aDNqVmh4ZnNJdVNaaFFJCk1kWmlxNWJneFRKSm53UEkvRkNw
            UXpZWXF6WXdpVUhDeHFDeEdMMGRCbUkKLS0tIDM0TUY1WDQrQ0hqVUlab21lWlNL
            b0lpelZTa0M2M3NtU2ZHclRONTV3NG8KaNA29rvCRqPrlvPyaZ3tHM0wZDRJiqyF
            pz1Z0mzFzU7t6KQbxa+KfBlWRCcX5jliwfNU4OQZX2DwWgFiqdtIVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T02:13:06Z"
    mac: ENC[AES256_GCM,data:U8oOFcp/8NkuIpwBAtyD+BW2xAuDU0XnUDZ7zkBULUhhD96TMuYo7z3GEtGyRWhK/MjLgcULezwJxej2kl4XUEeBtHHETnCTOVkE8dRUVSbo7OteNt17Cwpd3XZwuiXYVEmcfSaAV8Mfa1Uog4NA+ZqWGm2nUGyxd+VQKOeoF8w=,iv:W4+Qu5SbIAlPVDSwLXLYXGtp/FuuR5R8LtrjQbtSM14=,tag:NP0QQ/r2mM7xEo/zsN2EMQ==,type:str]
    version: 3.13.1
