apiVersion: v1
kind: Secret
metadata:
  name: bedrock-env
  namespace: minecraft
type: Opaque
stringData:
  EULA: "TRUE"              # required for Bedrock image
  SERVER_NAME: "K3s Bedrock"
  GAMEMODE: "survival"      # survival|creative|adventure
  DIFFICULTY: "normal"      # peaceful|easy|normal|hard
  ALLOW_CHEATS: "false"
  LEVEL_NAME: "world"
  ONLINE_MODE: "true"       # XBL auth
  VERSION: "LATEST"         # or PREVIEW / specific version
