apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
  namespace: minecraft
  labels:
    app.kubernetes.io/name: minecraft-bedrock
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minecraft-bedrock
  ports:
    - name: minecraft-bedrock
      port: 19132
      targetPort: minecraft-bedrock
      protocol: UDP
