apiVersion: v1
kind: Service
metadata:
  name: bedrock
  namespace: minecraft
  labels:
    app.kubernetes.io/name: bedrock
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bedrock
  ports:
    - name: bedrock
      port: 19132
      targetPort: bedrock
      protocol: UDP
