creation_rules:
  - path_regex: token\.sops\.yaml$
    age: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
  - path_regex: \.sops\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
  # Terraform bootstrap secrets (dotenv format, fully encrypted)
  - path_regex: secrets\.sops\.env$
    age: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
