apiVersion: v1
kind: Pod
metadata:
  name: pg-recover
  namespace: authentik
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 0
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: postgresql-config-pvc
  containers:
    - name: recover
      image: bitnamilegacy/postgresql:17.6.0
      command: ["bash", "-c", "sleep infinity"]
      volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
