
---
apiVersion: v1
kind: Pod
metadata:
  name: rsync-helper
  namespace: media    # <-- change this
spec:
  restartPolicy: Never
  containers:
  - name: rsync
    image: alpine:3.19
    command: ["/bin/sh", "-c"]
    args:
      - apk add --no-cache rsync bash coreutils;
        rsync -av /src/ /dst/;
        du -hs /src/ /dst/;
    volumeMounts:
    - name: src
      mountPath: /src
    - name: dst
      mountPath: /dst

  volumes:
  - name: src
    persistentVolumeClaim:
      claimName: media-root-pvc   # <-- change this
  - name: dst
    persistentVolumeClaim:
      claimName: juicefs-media-bucket   # <-- change this
