apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-cert
  namespace: media
spec:
  secretName: jellyfin-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - jellyfin.home.dcxxiv.com