apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin
      version: "12.3.2"
  values:
    persistence:
      enabled: true
    ingress:
      enabled: false
    extraVolumes:
      - name: kube-ca
        configMap:
          name: jellyfin-ca-cert-configmap
      - name: media
        persistentVolumeClaim:
          claimName: media-root-pvc
    extraVolumeMounts:
      - name: kube-ca
        mountPath: /usr/local/share/ca-certificates/selfsigned.crt
        subPath: ca.crt
      - name: media
        mountPath: /media
    initContainers:
      - name: update-ca
        image: busybox
        command: ["sh","-c","cp /usr/local/share/ca-certificates/selfsigned.crt /etc/ssl/certs/ && update-ca-certificates"]
        volumeMounts:
          - name: kube-ca
            mountPath: /usr/local/share/ca-certificates
