apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: juicefs
  resources:
    requests:
      storage: 4096GiB
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-provisioner
  mountOptions:
    - vers=3
    - proto=tcp
  nfs:
    server: openmediavault.home.dcxxiv.com
    path: /export/Media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-jellyfin-config-pv
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/jellyfin/config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-root-pvc
  namespace: media
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-media-pv
  storageClassName: nfs-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config-pv
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-provisioner
  mountOptions:
    - vers=3
    - proto=tcp
  nfs:
    server: openmediavault.home.dcxxiv.com
    path: /export/Media/jellyfin-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-root-pvc
  namespace: media
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: local-jellyfin-config-pv
  storageClassName: local-path
