apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-provisioner
  mountOptions:
    - vers=3
    - proto=tcp
  nfs:
    server: openmediavault.home.dcxxiv.com
    path: /export/Media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-root-pvc
  namespace: media
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-media-pv
  storageClassName: nfs-provisioner
