apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  selector:
    app.kubernetes.io/name: jellyfin   # matches your pod labels
  ports:
    - name: http
      port: 8096
      targetPort: 8096  # container port
  type: ClusterIP
