apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      version: "0.x"
  values:
    replicaCount: 1
    clusterRoleBinding:
      create: true
    config:
      unsafeUseServiceAccountToken: true
