apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-ca
data:
  authentik.crt: |
    -----BEGIN CERTIFICATE-----
    MIICzTCCAbWgAwIBAgIRAPYl7NaEb+5Mi7SlpYo74aQwDQYJKoZIhvcNAQELBQAw
    ADAeFw0yNTA2MjgxNTI5NDZaFw0yNTA5MjYxNTI5NDZaMAAwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQDFVAXvrxtjXWGLKOD2toyJuamdn0Y+an1vp4M6
    WvI1KtEe3FyhP6FhHTEeM/wZxBe69uPfY+y4ddDlWNishQFXNJ28Ey0kDhYmk6Wj
    Oo+upmBffYHHjEDgKY6rrAejF1tapaL9fZit50Zrt18Zv2CFJQHyWc7PKGbcBZB5
    H9LiIFuiMA7F/ZxtFCk8HxN/6mC5WcyM8mCZJK9VS7YlJ6bFeB/8wdN9ua5lCs0a
    3bJP73+340IMHER88Su6s0gpIZPO3FlbJenWHrj/Gb57qLStdycYcDJx2UYftA3N
    O8ddLUROmL/MQ6xxtVoSTXlUMHtXn3hxvRKfC9RyCN9Omz/DAgMBAAGjQjBAMA4G
    A1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMCAGA1UdEQEB/wQWMBSCEmlkLmhv
    bWUuZGN4eGl2LmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAkTag9k/2J1daYz/IqGS0
    tEGRnFGIcp1kVFgn3dWOaKtCkfVENKk6jiZdpRL5ndrC6Ak3Ag9shxpQb8DF3nPB
    YHQ+vmyWh1lQIHrq5yzeso7nYQe9LEIF6IJ+crxqY1odxo324a/OihPSfjUbyUcQ
    G8eixl/gQujwH9aceFBFEShkQnAwNv90dNGpUfoZ9KXgdhlZBQZzbHk3H2Z8naG1
    NrU/LeQY2anPEfHrqPmWPwHJszjFrH4h+s1dfkseADUDiLYWZATRvrXSXjpXI+qq
    fWh5F64NJeS1LWRM63tyGNJ/3ux639rfxnTgqE9evtUgmxxric0OuMWaUG6vaMAz
    CQ==
    -----END CERTIFICATE-----
