apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: id-tls
  namespace: authentik
spec:
  secretName: id-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - id.home.dcxxiv.com 