apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
      version: "2025.6.3"
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      valuesKey: secretKey
      targetPath: authentik.secret_key
  values:
    authentik:
      postgresql:
        host: authentik-postgresql
        port: 5432
        user: postgres
        name: authentik
        password: "zQUy5X0o6ESHOkHqQmc9rnlXdq8BjLB44GuVliUeC4o="
    postgresql:
      enabled: false
    redis:
      enabled: false
    externalRedis:
      host: authentik-redis
      port: 6379
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - id.home.dcxxiv.com
        tls:
          - hosts:
              - id.home.dcxxiv.com
            secretName: id-tls
    worker:
      tolerations:
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoExecute"
      resources:
        requests:
          ephemeral-storage: "50Mi"