postgresql:
  enabled: true
  auth:
    password: ""  # Will be set from secret

authentik:
  secret_key: ""  # Will be set from secret

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - id.home.dcxxiv.com
    tls:
      - hosts:
          - id.home.dcxxiv.com
        secretName: id-tls
