apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cert-manager
type: Opaque
stringData:
    #ENC[AES256_GCM,data:4CjsCWnbsVGvZkMWgyUJBYkQaMoDdywUJrO17r3s4SSpd6ymDRXexQjV/yAf3ScF1WIxXOJ/WQ9OnPM2u5E=,iv:g0iE+M/HOxeqRXAzQZAVE4Cb5D7EpMcOLLQnJET+E2w=,tag:UZju7oNimmtMSNaB7VcWCQ==,type:comment]
    #ENC[AES256_GCM,data:mcJUp9rshpLbDe3lKID4fTRJiap5xrF5mpGahHgzu9EHWNdC80qJAThHCuwL5ZPwoE7NWxy8,iv:RV7KctoVq+gLQWFvI5xm73IHleL1o+prRRxxfLIsvX8=,tag:bywnKRigb+vxQ5LJDRU19w==,type:comment]
    api-token: ENC[AES256_GCM,data:z/hCJsILKw3D4yCMvlAmFP6JJ7TO5rpu1nR/roU=,iv:f5eJbwJNYiFzIPfqUx/+LpHhZIjeNP4F4AxqdAx8PEE=,tag:RTj0oy87Lgu8PE4Hb1PO2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdk5aWVFSSzVoSWw0bTFJ
            WWJoNTFNOG5BM2ljNWgzZ0R2SXNTVHpyMFRvCnc1Y1VQM2VnZ0Z5TC9CQmVxYjZt
            bzZmOElpRThZbFZBMmExOEhTK3RzY1UKLS0tIGlkcmhkMHROeVd5bEtCRU5MeGYz
            UTFEWUpaYkZPY3N2M3BROXBYbjFEUGcK7SDEkH0xfjBrhygH7XDHhdHyihrjdV6V
            t9YXhWvzJUC+2JNJGcGyWJqnd4vpwkA7VKtBToPsoe1ArUxTYDZF6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T23:34:32Z"
    mac: ENC[AES256_GCM,data:ouGJXQMXDGvbLe7ova/1vx1iXUGujCSWrZbYUgIiF47ZMwqKkhYxJ5kgfRJD5d8c8lFYbqCvplMv8kwlnF+UM0Vl6fuY1icK5iQdxCXOYqkiMLhXh+X131zK2qhkQkzNna3GRXjfWNYS63/+jH2p3tZOyWCD8gL2cgF2mYy+dY4=,iv:m0fa/REi415jNVSuMNkptNwlqcB6J3I/DRvOnLhRD90=,tag:3+fzThBZuLxz0IClwaExIA==,type:str]
    version: 3.13.1
