apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lidarr-cert
  namespace: media
spec:
  secretName: lidarr-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - lidarr.home.dcxxiv.com
