apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-shell-cert
  namespace: web-shell
spec:
  secretName: web-shell-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - shell.home.dcxxiv.com
