apiVersion: v1
kind: Secret
metadata:
    name: juggler-env
    namespace: juggler
type: Opaque
stringData:
    #ENC[AES256_GCM,data:iJXdbXG8rdEglghCC5U9L7Qzl0oO2wYgo5Tc+t8vqMSH+MnWi0tzwPhl95Qost7Qz2W1fYIndN/w9QW3kCeT2Q==,iv:NX+1bgCuHYRIsuwOgEWEN4tIz+U0w2EJRCdT39HZ62I=,tag:+c3zeHIdk+qkNu3za6bbgA==,type:comment]
    #ENC[AES256_GCM,data:DgS6lbyU+MRFebJCG6xnTnVtXQSdWY2TXWHR9/FEXhrYDhw9hdodXrqzxraWjI3IdcrXbS53aL+2Ue8TkkL6KXZvvHOvcwA0Lw==,iv:SoTQ6uwD6Jdvsbg9so7hnIMeVDuaBVX0wDy53juh2jU=,tag:wAEAwoEbUmQmjOvOs2sToA==,type:comment]
    #ENC[AES256_GCM,data:nkMvjK+EWIDyqOkpkCXdbMc6aQxQLAgXJSI67fZsAAk4Uiv5mhSj+oc7SGxX9OPCAJ1kJTyHuBEZ04UNEbehfvyhv4xR,iv:UR/oLgdaVv1kQnXdqOspO2TSbZVA49vqEOsC+s0owVs=,tag:+SQTENb8XMfcV45IsIMRrA==,type:comment]
    #ENC[AES256_GCM,data:11ozLoRZAv+cWJ2l5CcBhe8DVeKg3ZKKdUkKp8D5e6t/FzJVi6NaFfvnMOzhhcp9VbJPPzxWGxlCnj/4exVQEAkUjv4=,iv:Yu9IBGYtOBjwmHxIHzniLZRT9FKYQVdfZzjFQNsDHa0=,tag:QZExwToh0ID5HeIJ6U8DQg==,type:comment]
    #ENC[AES256_GCM,data:k2EMWzOhDuagzhkghG7TdhlkeWGzlIcNZUV1i6wWxhVPtidiGFssvlMIxuESy+3njcLXeZOVpnlsxRqgBkptizCdAKr3RmRY9fA=,iv:OwDowYRzOA5UAQxoMf9KNr7Dmi7hbNXWxAQDQE8hG0k=,tag:AhJO1OD0C2ZvZ9a/Kg1qtw==,type:comment]
    #ENC[AES256_GCM,data:VSoLQ3jMnqUaBWuFwWD2sAiZJNLsbL6XlHk=,iv:sXFmYowcjG8NQh4/aklkIziBnbHCjyKQCDidW7M+kaM=,tag:S8LzrJInkFU4v07Xi/zkvQ==,type:comment]
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:paKv3A3UklVktMmGIyALlkgd9GsJl3SC9c701++NMN9mXVDJ6veSLk+PHLACJDNyrmtggVAkBKEnoLnMuZqHATOsL+TcVOLvbmuretl4xySzo+aWSuvN6uIzI/+4oCXhFnE2J4aZWaNRmv+D,iv:plJ/SzVr16b8LoCbmKtcS5u/bKZj4x/8uhBIvlrmqxg=,tag:lFOaoz8EqR5OBNlHL6advA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dVFtcmNOT29BbVA0RWho
            eHVLZ1dOdTRDVllSeXQzMWJFZmlTZSthNkdnCjBNTFluZWJXOGdXNFdDQ0NvcWZl
            OHFiQmZwM1NMN28xU2RYVFNDdStZUVUKLS0tIEI1MzFIbVI4SzNUVis4TWRWUGFG
            TXU4VWtiLyt0MEZkZ2c0am03Y0tsYUUKrhJf6vCD/u9JKnQZZhJsrpnfkfcq6rU6
            wI/3Nhql0OpOADeVCTHBPYRQBzLYnlvZFNp+6sJzNBscrAPEPzbhiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T19:50:50Z"
    mac: ENC[AES256_GCM,data:jeF/mmrD7YmJyT4BBxH2xbbVltfG1wFkP68bdgzqgKAiHQBKj6kIlNAeBAshVWNLSw4bVQpjxsLuAdO1S2NQLRXz6MkLUJOXN//sRBSK1tCawAp+Z6FT2g7To49bZxuUTnRq2nhoo/3AVFlquVM0VMH0EiE6oPlvGQ+XNM73BuY=,iv:x3/1RxI0PFj3goThxSMK0jcrQT9HaCXigbtpii1Ablg=,tag:WSODwRIIHtMz3+5sM/kVSQ==,type:str]
    version: 3.13.2
