apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dandydeveloper
  namespace: flux-system
spec:
  interval: 1h
  type: default
  url: https://dandydeveloper.github.io/charts/
