apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: mariadb
type: Opaque
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:PW9Fuj0kO59ayrp/D7lu0JK4Oca31+u0cgapaw==,iv:5bViA0Jrwv1ygEqXAEFPtXosFkFEiBIB3L7iCz0Ht48=,tag:xzFS+ogwrWaWBvpAWp2j1g==,type:str]
    mariadb-password: ENC[AES256_GCM,data:v2ZXm08N5hgeW+P7oyztvBlgaHL+guTUjQmQ0g==,iv:La+SCPNyvm15gzXodXdH9yNI6lXPkqvookT0oPx7XGQ=,tag:8W8VdjapPzc5ZFrNxnF//w==,type:str]
    mariadb-galera-mariabackup-password: ENC[AES256_GCM,data:LcE2lE+xW0p15mrqudCjE5W3ikotuF91ez5h/w==,iv:GdAHfudDjKdyLoDPEcKPQ6EvetjJcC1SuC2sB72fA9A=,tag:oCtSGX8jzSccOrgLNnxreA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bHF1WFpUOFY5OHRYQ2Rv
            cW1ZanVoSktFOHJBOUtXcC9OUUZ3UjlsNGlzClhLWXdxVWtmemZUcWJLdDJoZCsw
            L0RKb09aZ1V5aU5iTVpSL2pXVDRMbVkKLS0tIDhwKzEwLzRHMlU3NnlPSzhVS2pF
            QjA2WnR6WDZqVWl0Uk1VdVBSWEhrb0kKyBWWRS3G9K1fW7ya3vJZPpkXWyCgG3vV
            VmC2pZbo7KS3JFouLT2SoiWwAXVa9naJzVbzf0CA9UuePJ/WW3wywA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T19:32:39Z"
    mac: ENC[AES256_GCM,data:V2sPCswebKcNMs7ozqoViM4XUCRGTcu1O98aBn2tasylv8/KAJ2Hyevl2bpfX3w55tgsV9swLEkp5CyFp02AWDtQl1NThVk0nu/P2T8rvzbPYLB/ygVd232Cb7TUjQSD4u8959vIPZLoO5jMR25H+e8pUmn9gEWewBPUozdRXWI=,iv:BbHlGNLux/sHTULPNgjEyN1jeJmZqAWo0tJ5XuZX9aM=,tag:zNgSBgvzmb17lNi/Nbtfxw==,type:str]
    version: 3.13.1
