apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.home.dcxxiv.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      services:
        - name: ak-outpost-infrastructure
          namespace: authentik
          port: 9000
    - kind: Rule
      match: Host(`longhorn.home.dcxxiv.com`)
      middlewares:
        - name: authentik
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: longhorn-tls
