apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: kubesphere
        namespace: flux-system
      version: "1.3.x"
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: nginx.local
