apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: "30.x"
  values:
    deployment:
      kind: DaemonSet

    service:
      enabled: true
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Cluster
      externalIPs:
        - 192.168.0.204
        - 45.32.227.185
        - 5.78.149.27

    ingressClass:
      enabled: true
      name: traefik
      isDefaultClass: false

    ports:
      bedrock:
        port: 19132           # Traefik's internal listening port
        expose:
          default: true
        exposedPort: 19132    # LB/Node port that clients hit
        protocol: UDP
