apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
  namespace: traefik
spec:
  forwardAuth:
    # Authentik Traefik Outpost service (created by the Authentik chart when outpost type forward_auth is enabled)
    address: http://ak-outpost-authentik-forward-auth.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - X-authentik-username
      - X-authentik-email
      - X-authentik-groups
    addAuthCookiesToResponse:
      - authentik_session
      - auth_session
