apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-forwardauth-middleware
  namespace: traefik
patch: |-
  - op: add
    path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
    value: traefik-forward-auth@kubernetescrd
  - op: add
    path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares-https
    value: traefik-forward-auth@kubernetescrd
target:
  kind: Ingress
  annotationSelector: "auth.home.dcxxiv.com notin (ingress.kubernetes.io/ignore, traefik.ingress.kubernetes.io/ignore)"
