apiVersion: v1
kind: Secret
metadata:
    name: anthropic-oauth-credentials
    namespace: strange-company
type: Opaque
data:
    oauth-token: ENC[AES256_GCM,data:8k+kVDfGIogzhAuliF4G5ZgHiKR7w08li4sV2y719uOd/ZG1wlO4l8s5k1u7rmFKj+6FYiL09qO3njfiwwBLv6/EG7Z30NcHbsIhSycPtheIcwxY8LuWQtiZfG7KGGTfqNC1+rVSm8SD87DnUQmWn+f89E7T+M+SWRaRDGewsNfZIjWQTbghRMWVRn240zDJ,iv:j0FxemB9TSwFBvU48g2IjPbIURRh8mqjEHl8/BHhpK0=,tag:FJWW/x0/fJwl0y8M/yL5QQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSCtzU3lNa0YzREhPMW1q
            ZXZJVkhCS0p3NTR6R2lad3kzdzRyUWFEQ1Q0Cm9hUGJNUnlmdXRZTjdVWEx3UmVK
            Sk5zNHRmdERhbVNER2tYMDh0bTQ0dTAKLS0tIHJtUEhRTk5YRHdyWlMxWkFiRGNP
            dFJlU3Bhd2V6WUIzSGcvTksydDdOZk0KNEaDPYoPpRYrZTgozmkePpA/tXmdhETp
            xhCUXRGxUnv2WdqX3nhLtptTLz9Gh9gukStODuGlbdaPvJjyq3wsCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T05:35:27Z"
    mac: ENC[AES256_GCM,data:2Io4D5kBQt6rF4z8DBZdEVIy7KOkonQ66F9S5/iN9kx4HErj75Wl2rOhs8aL4kjYrUp/3Ybks8TGnlRoSpZ/lLzieYWpb9BXXj3d6tbjNO+t1euVs+qKEat3WyW2Ur48RYm3VrXkRH08pMRQHETTD2TRAXjjR8fIXocmyfvD53w=,iv:9r5Cs7uDmfjg8iQXCF+q8yIrdpUkM+pAwyyH71AzsVU=,tag:YxPxdP81d5aBXPYGYbhCcA==,type:str]
    version: 3.13.3
