apiVersion: v1
kind: Secret
metadata:
    name: strange-company-db
    namespace: strange-company
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:obVJHDJ1HGYMHbKMgdTd,iv:SZq7wZL8I9Vn1gJdzCibyPGVSkYNijLEw8qUeYkwCqo=,tag:xEwlsotalCG2QO0Qij3a0g==,type:str]
    password: ENC[AES256_GCM,data:VjbVYXEefauBxBELSoC4a71gzQ+wcU9KH+WJBSLVzkM91uz+qqAu+A==,iv:EBKvVPYdvi0NpP3AYqOApE7YDyJHXSYLgJgBRZUWUSk=,tag:4oSnLW05rg8bJrhZ56Qb2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQVB2OXFjQmhLd1ppVjBK
            Zk9WbGc4eHkzVlBvYlJReXlvelRNTmhRb2c0CmpiYjFPQ0NoYWYzR0s0YXMrRis2
            YmJIeTBQRmVCS1o2VDJyMkJrV2JYY0UKLS0tIG9HTiszRHg5eGpvUWxBUnd6U1Yx
            UzROVklhRzlWMi8vMUZ3WmNTNXNBd1kKvkZ2qHaLL1+UYXsB+22LYRAG2cCeRZMo
            /58yjT9XQoXfHAZjRXbFSAy5ehTi1CtSR/IZf7vhD39NeHpBLPXSQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T01:07:42Z"
    mac: ENC[AES256_GCM,data:4pZuD+ucQjpQSK5lNqGm6wmnn6g4rMhNKCinGJk3uJO9VPU0AhnVS6O0hGquKa68lPBdciKQigKVWsOjgLIe80wEvti+b8FJUt4+DpCpc3/dnnZ3EEHx2lCv3wlG74D6dGvwBnaZZgSiBob3ovMIpVOHa0jNbkSQbilHdDmsqRc=,iv:AqyevPsM1swb/oehqtrXc9bH4RYjJ4LRkhkYls+nUTM=,tag:2A/HsabuaaCovSn1mMS06Q==,type:str]
    version: 3.13.3
