apiVersion: v1
kind: Secret
metadata:
    name: deepseek-credentials
    namespace: strange-company
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:vPUAmyBy9I9MHifF4296oXlPOTUsrNHTzYOO2IERIHUMWoWL5KwWu2BRfJvG3c1R,iv:ZeAnp1NiRTtDrBhu2xQcjE1FsSeD3qvThbc7VCorLX8=,tag:2QZyK8HXjS0w9vtWygxhfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOHVBckNFRE1ISUovUWdC
            M25FMFpLN1lDVGdmdjgzd3gvRGJDc1BTTjNVCjZiN2wxZk9MVW5PbWZ2Z0xmOFg3
            UVhreVFZVjFRbkw3SzFCdHY0c0VVZkEKLS0tIG9vRW1kRzdFakVvdG9FclpjUGFH
            Vm5oYjR3V1FiZzg5Z1JZTGIrYlh0K0EK2OZD9i42wQuQc2SiQbak2W9eiNyad+Y8
            vlhD8llR+DX6yWEQQ44BzypwhBwjlYS79BEpMx4n5bkS+ixKypWolQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T05:35:27Z"
    mac: ENC[AES256_GCM,data:LE/RBKqPKjVrpEf5y/FVnzxLtjcCEdtSqmrCa3o8RMKdwqIKVPUUL/fDZ/OV69j+8M84PGVPpoQWEMFECRDQbcbg0d6FMEzRTSWMmwsN49iIF0Tl4jaHqKle+hVgdpqmASEpcorHWy5TzQZLB4PaxOkfFj/DY3Mwd5yFr2NbA/4=,iv:h8d6ZvzFHtYX9PxHAndiqZ6Aqtj3gM6meWbvpyVpOI8=,tag:s4TNuTKnXF8LXBCWnd0ung==,type:str]
    version: 3.13.3
