apiVersion: v1
data:
    github-token: ENC[AES256_GCM,data:fwYBh1LHlVn/ZtEF1FDZgJSA8kIKGZqxTDCYErxSxFH4hsZqDJ0Ox020ZCwu8AEouQqs85aFX/Y=,iv:OzW7c58X9zGzmVck9MOrAMyqOsd/rZkEUcYJ0uQIIgg=,tag:4eiX5d8YP888xgUuSpYGyw==,type:str]
kind: Secret
metadata:
    name: strange-company-github
    namespace: strange-company
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObEltemN5M01xV1EwbGNi
            MjBISDdkQnJCL2hncWJ1eE1Rd2RudzFqYUFjCnZ4WFh4MXFEc25rY2ZyQmJzRzR1
            UmcyZDd0S083WVVYZ0IwbkYxdjNudkkKLS0tIGNaT0ZRYWEzY1p6d2pGTmZRNGlK
            cmtYZDRTODV4UVl5VFdOT3gwd3lNdU0KSG5B9KsgSufZqPeDNtFFMraX0A+cWW2G
            5EfnU/SK7i7gJl1w+hnRjUGaTjr9IOH0sfsBcfFDByHdH5VqyjLjRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T21:08:39Z"
    mac: ENC[AES256_GCM,data:Z4qNzNM/8A9//UoybIDXvdn/J/iAKz3SwcAU98Sb3pAhQNoVZTO4oJ9D8T8MlRWB7vMzO67lp+/zZFTN1u/m2UwBDZWzYRRFLZUYs12lTnOjfI/WunvGRc8OVmyR8+TBalWQaqLn/cX/u8hkcsYZh2Zmayg+OvWFuOoWXPfY0LU=,iv:ERQxwVsgY9ziBg9yZ6mBbttIXUt8gWZV9kPhpkZzgiU=,tag:24Nr0Q8VslWxVhWHcDqR2Q==,type:str]
    version: 3.13.3
