apiVersion: v1
kind: Secret
metadata:
    name: strange-company-provider-creds
    namespace: strange-company
type: Opaque
data:
    deepseek-api-key: ENC[AES256_GCM,data:pHigUZeUIe+VfpZiT/JsXFaZ+6LzQAk6E/s2jMY/VUzQf68f2BPGx8DXkqIebWSa,iv:yV9CUvFKoXz3Wa3xyowRxkGWFQ/2IHiwroE1RAli4uQ=,tag:Pb4Vg9kV2qZvYuRhptBRrA==,type:str]
    anthropic-oauth-token: ENC[AES256_GCM,data:H67bkIDT2hX1kno93sGdiImUOsizy3GMKRlSM6+ANxpVogMz88gme6jrAOkZzqnHRAu+A5pnZrHqJp2AmEdC9A9Pvkui27zwkQSwHdNHD0fuJDpMZTfg608i+/MA/8JpM/SslwG/kmXuURTTxOIevqZR2GGs4o0xWNn772zywea8vvx6pCrvB6fCjOyW4JJT,iv:eJa6BEUEdBu9b5CIjlLot8iRFDFf0/KEqfyVjlngNlk=,tag:CLYuaZoPhZP1v4sP9JeceA==,type:str]
    github-values: ENC[AES256_GCM,data:CVqqVMd8S5j01YOpZDO4idAKDuYefAqu2RgNu3/G+ptd9FGGx/b4ddOqLnj8xmssbM6PLpYt9icD4V377dTKGwqxlIyTGC5WZW7splblunE1cPA2eX5b90OJPj5E+JLbbslAAgqxM2D6XT3CblozR1EjkBmcO6o52jVF/1+uWm5lJT1NsoQmgIF37OuWRz4k,iv:8T86zbQFI9ytzTtoOZnOVEj/Uhg5CDrNrhdFV1ToEMo=,tag:+xjD0VW06ewhYCEWLgJBFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMnlUYi81VlNvRXRMWTRk
            SjdPS3ByejZ3c1lmblVkcjByL3NUOWRBaFI0Cm9oZkg5V1ZPQVNiTCswdllPdGFz
            YkZKSmF6TzBwU0NlTWY2VnRQZnZ4NkUKLS0tIEF3K1ZsZ1RCNnJSTU5HNW9jYUVZ
            eU5tbFg5a3pxSjJaMFJmNHVDUUh0cUEKJ+JOQxNYf+qIZFD5NrZZ/fimoZzVPHjW
            2fOJ1lGDi5Lx0U55aWT+ne9xRkWqk8DECiG/adhclfNrUNWcpAO3WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T21:39:45Z"
    mac: ENC[AES256_GCM,data:BkHFhLRB22OmpmouNO+wK/AiMfNfupPjhwW4YwER/oJ7S+gFltnMgQhLe0hcd14fp4tJbvaManSdaBNxdi1zZJsiijMUUiwXkkDSCwtKSBX38JmZg8KdH0QLKer+CXhtKnem28dncG0Pd0V3dAfC6/iVQp5g5G/uL6cREeRg1GQ=,iv:xs9ThiQutKekU2+wsVCdupahNd/z3Bzte0ov2ACpdYM=,tag:fx+5lKOoMinJzGmPJm441Q==,type:str]
    version: 3.13.3
