apiVersion: v1
kind: Secret
metadata:
    name: strange-company-hermes-managed
    namespace: strange-company
type: Opaque
data:
    .env: ENC[AES256_GCM,data:i5NpGa+HdJWGKvFWX/Oo/Bmn1lWfJSy0aJ1cTgFgPN9NP5PYu3HdWAeG+fA4LKOlc1NYyRO1x3vPO9a7jYwzCd/2XsVzf7rAmHkAlUZM+vO1aVb4wvkvH0PXWEKaCjaD/tLRlozirVSw4sW/y8/eJDm6lqGdfDjGQCPDkVfdeu2OufISYR2i0mmsj+T7gTFfbCM9kFC4X7feIsA/Cg9qjW/tce8dnsepOM/6fHSNSH6ylTUu1XXoTreF71hJy7rQJ2VyIP9W/97XXL198Qt87FKu78A890wn0rabIi+pJinzqzPJBdDN9bKxxm0z+QlXvGLUBUbOQCo=,iv:NEcfccc5PWwoYdFYRJDUt+PyqxS+Z8J6ZkyMP7eapRQ=,tag:Tjhhu/mo+ffnk+6Ia0a7bA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaGx3ZlA2VDZNTG80azZC
            VFRHTENIVVJodWtqRjNoUTNHYkkvN2VyZzFjCjdYNDlCNDJkQzA1RzF1eUNGNHlp
            eW1JNUxOeDZGU1dqcW11WWRjK2N5ZW8KLS0tIDJxNHpCU0dXbFdxbm50b0htQzFC
            M0l6Q0dURnVRemJ3MTRDb2RucXQxQzAKfXxi49ZL/j0yBIui+uaJkG24yp3iImYS
            EXZ9kbvSrOT0D5rRo+WFjbe1N2uTIcaACzc8Mh4x1Nspfm8C6tcjJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T05:35:27Z"
    mac: ENC[AES256_GCM,data:oPZy5hL+Bhof9sPX3jjmHaXYYEOPXrqZMVPD/Kq6Oa+IqqvRdrjiA9yE4lcOHmzceezf7SznzHGymFMvxhyXsWBKyE3UY1N+ByyYFKRmgEoga5X1u8bjJEPSU+nMcj6I+nADAufTQxXMeSOSGh1tLq6oswvp7qJyokiXGXR05Nc=,iv:mn2wzQLNSJ2o6mdDXvVJDW+REFsEYH7JuIwQrGPYhHA=,tag:rrmuXw6trTV7IGIQBg8OTQ==,type:str]
    version: 3.13.3
