apiVersion: v1
kind: Secret
metadata:
    name: strange-company-provider-creds
    namespace: strange-company
type: Opaque
data:
    deepseek-api-key: ENC[AES256_GCM,data:M4wPbPvYDZx7+jeLakolYWhpZt7z8KxV2eyxzke5RVG9DSno0fnBTeODMBj8hGIO,iv:wC7B67595SIo3Zd8a6NjbsMZFaIPPW3OPoI8Ds9qSvM=,tag:11qZewPimwmfNhlqcnExvg==,type:str]
    anthropic-oauth-token: ENC[AES256_GCM,data:Wv15UltVp4PdmvrmuRfssv/PI2GHLvjFyYiunaE8KdntVVD6+C1RcwlqHGhtSAp6iPxlJVNhBJhPE/IRaqkQw9v6LQFMBGBeKkcN8tZGjvTuxvZ92HPgJzpQZ1dka/8SZpwihZGmXO+DnEs2IaxaSc8VCtfAT1r6kQ1tcbudcQlcWX4CkTS3Z52xJGODXDB+,iv:+0ydaSF1hyHl9PyVU7LTZ0IdV71Lt9jAGNy5WTUJ2U4=,tag:aaDFdfHKrkTbP8pFsAcRqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMTNTZDkvRHcvV2NNL3V6
            c1g1VVdYclRrbUs1blNPVitNWjBNZ1VuZVRJCkNnQ1RsbGNkdElGOWFtMldhOUIr
            SEgvVEtpaTBDaFVrc1VMZldnZFdVRGMKLS0tIDUreU5ZcjhZMHkzaTU3T3k1NU9F
            L1hEa2FwQnR1a2VLU0VldGh4djZySTgKX1BSTm881ORB1hMm1ZG7h+S+7LF5xjNM
            /Y4gXWVED8Kh/ilQrPUpQIfTb56d9TzMUnyXGUa1HkykgXRFdhosmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T21:54:52Z"
    mac: ENC[AES256_GCM,data:3PhLMKvRFhPnFuOt2GeKs+2LuHb2SzERQB8aXnfGx1Wzt5EF601m4codf5MsJy4x/v88HR6sJHkZk9WH0zLHH9vQ35ZE+RWn6LuBPq5xDe829WeJBsLtzQvoLwHNdWf7nhgMgTtCw7N+2uHCuG1OTa4ic5e1ccpWvyE+YScwCGM=,iv:/aUgKNp02RI7jWLLpXF1VWSqj5rSu96MLzRkWMm59SU=,tag:gPf7FHmniHVlZoSHHOToYQ==,type:str]
    version: 3.13.3
