apiVersion: v1
kind: Secret
metadata:
    name: strange-company-vikunja-oidc
    namespace: strange-company
type: Opaque
stringData:
    #ENC[AES256_GCM,data:vaK3iS8AgoHZT1IwgnrDNg26VRjS25fois2V0bZL6bqvqRaw/Q0ccmVd2S+kC0ty7tN2q00u7x+ijiuddBDp98DDKxbvzFJOwkA=,iv:PZ1dbrnDOnGNsyoXL8QMZuLdwvXPtL6sin0yZh773TM=,tag:aiRoTjt88NDtClKaOVaMBg==,type:comment]
    #ENC[AES256_GCM,data:VpTHHlKivbR7j9efMzeiEFd1LzYKYIagUoS5CXyFPnJID6ZWl7sJBUqsT8ExsVMR,iv:a3C6By7Qk1tbiIfzwnAgLEy2c4JrjRq6hc9MCFdSDwo=,tag:BI/gynqBf2vecoPphAAK0A==,type:comment]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:6V4i0Pn4wWM6baQhTsn8wHSatgh72FIHeXy0tEpNgZDnfeWazLWtHu9dFDkFmoltY30=,iv:3YaXT7wkjeMX/Gn46IJAG/tfWnFlQTmetUOIlgPiDA4=,tag:bnxRjh2fjs1/62RHwe48Ig==,type:str]
    config.yml: ENC[AES256_GCM,data:hMQrCCmZ5rvybKSo+hRH6svjGLiM6yUF7POdfhzcFMirV8ZkhwLLFwjiR9eqF6ccYnOfurMOT9+bCvLArWOsICcYPfGNJbRG2eytXY91IKK0piKtKugGSG+jxdo3DqQeDA7CPyjJwaWvNxM7Ba/hg07s/KRsmQAfoYiKpF9WGFEEjYAJCFSKsV7hVn6TcoONBF0BiaTLV3bT0k4IO7lh55vweq9GLiyAYxxF0eYG2Yt1mLn+3rf20+om9uiRWVCo8HDY0UiMbYshUSRlSujsE5OIqR87MKSj53JRhTkrOZiVWiEkov1fD3blcKXJ0GXaX1PqNgamnYrUnKNqFibJzXlHO4/PusUJcyFFuEGAmap9DtL1feOQ4c4lkNpquCa8frdvU8TfDplKZ3IoOy4b6XA6PUS+0qj888F6a5e9bvCNeqjfnfqRng+AFQaJtIwY/7T20GrHAU2fJYJgJqq0JoijwbO6bh4+5f0JVcG8plu/3p0bq+RFrtfBV1hUco0xIeZpUXn21SrBRuVpu4zYlhT9rEDIuMJkFHLH/vac6LsuEA==,iv:qY+4HgDptDYWG5ViDjoRsktOePJ409ruw2e0U/byGK4=,tag:hzVBZCLPoiufl7ujPuRq2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYjF5clFmaXJHbmZ0R0ZW
            SnljaTJXNTFyY2VOaWQzempmV0NWWFQ2NkZNCm80VWpYWUVNUVQ5cmF1Z3N2czdC
            QjBIU3diZTBiakVBWXJFVDVoQUh2aTgKLS0tIGRyVmJYemVHa3NxYkhNWVRSRXF6
            cHVGelY1NWhsTmZKelYyVlBPM2VJSE0KjHYzbC0BlvRU7RLFytfhu5CW55wAUR9l
            HowamfrghwuL0hr2AlsuQqYJlRyzPle73M2zyI/8W2Bh3tHZzWgasw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T04:23:57Z"
    mac: ENC[AES256_GCM,data:ylpGpDOFdlYwXXmMaFUQUMGtzlBOs1eNyWxcPQfuWaIp0qLW/cB5GVisyZrTldDcvu8zWlzzp8jmLoFLZnVYcLckQvXNbfWRVFq/u2LB12qJNQ1jW6VzV8wCUtU2GF2f5+TOh2MVAnvJJGoD6CMqUSyCYVwp1A/tSJsMMYXbUHg=,iv:iqrV8laZB6YoKVExc5JvipQmmX8KIa5nA/WaUaKVp6E=,tag:X+U/Y9rNRWkB6welhi2AKA==,type:str]
    version: 3.13.3
