apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db
    namespace: strange-company
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:2xQtAFNuT2OQnvgeTQHQTB3uLR5VTruP+s9ZLYRp2QmyZxv0EpJVvA==,iv:tIpd0rZdfq5IW19i+Y5rBj/EZgNZ8Sn99D3mnippgOI=,tag:/2hmMCukT4+5N+z0ssCnFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNlFON2xLUFlINUVyRlRV
            WWc4RDB0ck95VE5LT2l5UHNES3ZHeStheFFrCk9yRUVGNUcyM0RRRVRwa2dpWHFM
            YnRMWEc3TS9PcXl3QmJ5UEx0QzQ3aWsKLS0tIFVTVFlSZ2FPVkNRNFBiUXdZcDBh
            Tm12ZjJzK2VhbHZhcmM3eG9zMEFhV0UKAzbGbVu+qpICt2P7JtJXMtJWNdBO387w
            NXEZFWu8Kz6IIt1t5qwrSjUmMnkWnYpsdXp8uGbNnF+PvVDcNo0y3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T01:07:42Z"
    mac: ENC[AES256_GCM,data:zpPWnQAXO7sZuqdnfe+AtQPLyRWALwgAScof/rwQK81sWVpqQzPROYANht9E3eFQkCJofclKQMABMNP8rkAJ01kpFsesB5Z71rPjIniNxiw80KIIL6BUA4t/NAzFELuY7eK/m3BWA1eNnl+CAR7qXDth5UdSNbUCMTKpzGh2QY8=,iv:wSAZ4I/qThaSiD4jPSlkXYEWH0JXnY2MgHSjEbY2ZBs=,tag:WBsMImazkSJxfc9TGicCbA==,type:str]
    version: 3.13.3
