apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: longhorn-system
    labels:
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/component: backup-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:T1lHHrO1nYnMTTzBTLOKLjdE4jvIlFGO0HyzsWBFe+qtF5bhlCFv3XlLpDhJZTt8Qtp4SNF8OWwkblZZ41wo5w==,iv:HMQYsp3G0+KKdVP3MwipRZ8og9cffTJXfAdn4AfKGgM=,tag:mTlJRDl+hrLFSZvUV/VJ1A==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DTLTtw8a0jERexlunhJRnE3Wvdg=,iv:qE44cpbCqi3T+2koFZ/hfrraNzwd0Ptd9j/x1AcKgws=,tag:+cAw5HZlLHJvK7jRIrmtfw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:z4wEXF2VmUVjd8+6OHFXhyqiQ1b/MISRNX3XzXyrf1N/gpT8IDNgHQ==,iv:IDpR7N885ta8Ypjw77/V7KgHOjDRlZ7fAD9AyFVmNqw=,tag:tRfUqSaBa7fVCjcJ4+nhEQ==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:CnM2rawlQ47W,iv:cfwdBYu+XU0I+/OyJa7TmdCLpdre0wZ1R094KT94rbk=,tag:25rWuWvvM43BD1r/ilctUw==,type:str]
    #ENC[AES256_GCM,data:F7AFuYTOQJ/XvRcAWfRd6xdGDV4FHKRNOstzoB9VROpWhH6SWWvGaZ2a94Ewj+TMDu73rUSG6KL9uTueiXnR78DF3f60+jdCTZGGMA20AYIA,iv:XMu6lXnyW5CISM/MAVHY1hNxnPVfsRjDDDBJXf2U+oo=,tag:a0/l48T8G4KP+lCJsvFaYA==,type:comment]
    #ENC[AES256_GCM,data:axJSw7bPkgeSdrKXWgsfCOuHTV54pc226q8Weei8+EWT/2IqfAxbUUKCxjGa2LchE2V+1W9Sc15sqx7mZru0JK79PTPC7Qf+Xg==,iv:VloPTQi1QblLJ/eV+hG12B/3cOavO0wds/Bldfn1mdE=,tag:Dl3qBo6DRmKaYFVKiu1+LQ==,type:comment]
    #ENC[AES256_GCM,data:961Wg9RdLL31TueCIN87DQS2UKk9TYYUTtg2azzthZBARLgvQDbBejLI+yrnUB0cx6qjXfcsicFRwg3zRIN20um4LynF6RlLr920YrMeu/kEMLubZjk=,iv:0RZL1UUuPp12qmUhZvEkVEM/X/yy24WAJTbeFFEK6F4=,tag:I0fNZdOOGLDat5zFfHgCKQ==,type:comment]
    #ENC[AES256_GCM,data:XUSQsZPgo/KA7gMP1dZGXrkPNnnQqmg87NKXVGMjaONE42NDoQ2Xw9KMxaRgq2TpUNyoM73MxkZ1X5O749kjTHab6dHavPFU5oH6dIkPr4GrvCYFlMc8,iv:acYvlXXTzhgZhfCIMzU4A7aF31PtncEz6WmYI+86Jos=,tag:ijpLpnb8Ze5BsOhZi7s4Zw==,type:comment]
    BACKUP_TARGET: ENC[AES256_GCM,data:XmU+uZ1hQ1J8A/V6rfqDcfWDLKGjjmBIrbkPUhaSS6eW6MoOBt1l,iv:TCDeh3nRz6wLnsh1r0099PM7NKAZBU9GcUB/bBKQzys=,tag:74v5utiRS4kG2j0yiRhW2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MzZ3cXFWMFVrejhQOUp2
            UWxrc2JYNXlYdC9Va3dxMWkxRjBWUHlMS2dBCkhlVDV0QTNJNjFReXJQRjJ1UkRL
            YnhaL05PUGJ6Q1h6dkFMTk8raVMwaEUKLS0tIFg2Z0lJSE1ubGRQQnJIellpQXZs
            ekVFamwxZWdUb01kOW9hdm5LRU0wWm8KsUuvnIOjURBzEZZWTYpWifSBNM03Cq8M
            /Y9PKB+sIrdNsfh69RRhA6OLysrglQhZIjpwUYBUhD9NtXa25WuDKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T22:53:48Z"
    mac: ENC[AES256_GCM,data:GkKLNYBouWqobKt4tjNQ4lf1J3pbWE+95xvTBXFpb16s1x3YeRPmGhRRwhSmdZJOpgYzCTGeMoaCETSplUfuEZTRExyO3ZbGhd/am4bENFrTgxDt0uvPjYctB25cu6C8b5FaRKwues9L9NCjfavOHdoJu9GNO+9PQX6iPVhnPbQ=,iv:Tk3Z2RJ+7Zq2nzz6lRvHYGN+C6c7DT8W/VXnXsnGd5Y=,tag:IUeO9S+rjCW/ABi3EX4IKg==,type:str]
    version: 3.13.1
