apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  timeout: 60m
  install:
    remediation:
      remediateLastFailure: true
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
    cleanupOnFail: true
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      version: "2025.8.4"
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      valuesKey: secretKey
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-db-secret
      valuesKey: postgres-password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: authentik-db-secret
      valuesKey: postgres-password
      targetPath: authentik.postgresql.password
  values:
    global:
      host: https://auth.dcxxiv.com
      env:
        - name: AUTHENTIK_BOOTSTRAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: bootstrapPassword
        - name: AUTHENTIK_BOOTSTRAP_TOKEN
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: bootstrapToken
        - name: AUTHENTIK_BOOTSTRAP_EMAIL
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: bootstrapEmail
    authentik:
      errorReporting:
        enabled: false
      outposts:
        enabled: true
        types:
          - forward_auth
      postgresql:
        host: authentik-postgresql
        user: authentik
        name: authentik
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - auth.dcxxiv.com
        tls:
          - secretName: authentik-tls
            hosts:
              - auth.dcxxiv.com
          - secretName: authentik-outpost-tls
            hosts:
              - auth.dcxxiv.com
    postgresql:
      enabled: true
      auth:
        username: authentik
        database: authentik
      primary:
        persistence:
          existingClaim: postgresql-config-pvc
    redis:
      enabled: true
      master:
        persistence:
          existingClaim: redis-config-pvc
