apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-config
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-redis-config-pv
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/redis/config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-config-pvc
  namespace: authentik
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeName: local-redis-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-postgresql-config-pv
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/postgresql/config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-config-pvc
  namespace: authentik
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeName: local-postgresql-config-pv
