apiVersion: v1
kind: Secret
metadata:
    name: authentik-redis-secret
    namespace: authentik
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:DFMf0jEsZhkgDQwYDYZNT9144kzskV+mN6qqa2WDUFgppE/Cwd6GpA==,iv:ANkYNZkd7G3Fwqek6tSGtc2EN8WMD5QVuHuLwkwhD/s=,tag:c14ex1yKmxeOe0TIn/uUbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSC9JWU50eTZKdU15OFZa
            a21uelM4aEVteDEzS3FkQ1YvNjcwd2pHRlNrCmNTTXdLZG5UdHc0RSszak1LRlor
            WUxOSS9Mejk0STRUcVhTcFRpalNLeFUKLS0tIG5hb0pYaXdxS1BKWXRja2pFb21V
            V1hmSXFoaUVhT1J3LzFKSUIrVzhoV0kK7Cs1ldGltIO7rjFkw21jIr0kezQT7ra3
            Z7nRdTagHlZk++aPTTflyvKrP7w0fGXu/QyB+AFH+RbeALiUZF5aHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:59:16Z"
    mac: ENC[AES256_GCM,data:GJfaTGmQjCWFnIa0KcI6aZamzVL5NsXjFj6IrRno/nEDi41B5fku2NrQgimrORoejUv/NBsDUcKVejaTq0URtiy84fgYfvHREZS9ox0ti8HtBarGWsJVHanr9GXt+DpM50rDaX+ToRon1jwwbSqkI7TF7qvMT0FE465Xa6WQ5i0=,iv:w/hNjbmVfKIaJOM+M+FTsqf5DBoGfjVFMgz3qOLg5sI=,tag:cchOUhgA3fEAFq/Ecj8kJQ==,type:str]
    version: 3.13.1
