apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    secretKey: ENC[AES256_GCM,data:8W62hQYU08NQHbllrBzDWKSnOXKxW7IM/jUiQJg1aGFOSdJw6J+J9+LcQqpOe7/HBRp4qfGJrJE5kLGdQthUtw==,iv:AWEq6E+iF34UhYCgXWsolvnULm+buDNc0u774BVH1R8=,tag:7RqZ6HNu8WehkcxLYduC4Q==,type:str]
    bootstrapPassword: ENC[AES256_GCM,data:7TvlVZiINoyliw6aHMNvfU6I9GWiAq1I1WWLVUE1XZ0=,iv:F3lvmfbgyhTeFZ37vY4NN2aNjUfkmzc22G4IpgA3LqI=,tag:vUUMhs1DJjMXRaReOBAgYg==,type:str]
    bootstrapToken: ENC[AES256_GCM,data:YT1ekUTbA4hEW6pBUZD4hDfDsqRX+bCLlObSXddAKH1Kqz1FK0tsguCz0A==,iv:wOTrAYvwFh3Uq04IM2bn1606BnqIRNq4ZZTtTyeeJS8=,tag:/bzqeb+i81ovf3u7WKJCmQ==,type:str]
    bootstrapEmail: ENC[AES256_GCM,data:nVoAwCEzrqaI3FUeXyLPIuhUEw==,iv:biQHU3545/sDK1BNjZX9Ir8sLawNtKvBm13MoOVC9DY=,tag:GNV10pu+m40o6v5UJkq4Zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL3ZnMlZGNU9tVk1DTytP
            L2NtYzZEQTl6R0dKZk4xL003MWdSNTNzK1I0CkQwTnpIc2l4TE50cUZqUHBhVnNn
            Mm9uNDIxM1NBdWo4Z1pBNndQRUNKbFEKLS0tIFJFUk5JbCt4eFV0MVFtM3lEVVJ4
            V2V2QnphTVVVSUNKVk9DRTNNeFNuYjQK+SbA21uigPe14Eu0QhrIlzYJU5/EFbSd
            OR3v2Uv0K2Bi8Kdu1njNMGCZWBAAbBQJch3hsKVT8UKsrz1jWMhuiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T23:05:30Z"
    mac: ENC[AES256_GCM,data:z8KlON2PzG5AL0kZY5DROuqoJnCDihOsP5xjBQOEoYRsLKosOuzZXunB7diWROhsuZxVJ+OWNGpKq3vcwctwaKPWftbZEhgNRr3FkkY53mBEpTEOqoZqjDKDTPHbcdJVe02JeR3X6PqrGXu7xiO68JbyfsWiRoL/1QqeEYcF02Q=,iv:uNQtHRebFHkuJ3zJoslycmYpiiGHwxjQfFesjIfT3k4=,tag:Za1w8MgxYyR4wKipQNYujQ==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:yHWoqkr3GC8UBgmxeD7T2N4mbrcX2eJtzf4UUzIGGH0=,iv:+8HdbKJIidjuDILeNMwg0CvNuCqkjkEsMAlQJxtV+eg=,tag:/7V0PiB20rPmnky+PQnXBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL3ZnMlZGNU9tVk1DTytP
            L2NtYzZEQTl6R0dKZk4xL003MWdSNTNzK1I0CkQwTnpIc2l4TE50cUZqUHBhVnNn
            Mm9uNDIxM1NBdWo4Z1pBNndQRUNKbFEKLS0tIFJFUk5JbCt4eFV0MVFtM3lEVVJ4
            V2V2QnphTVVVSUNKVk9DRTNNeFNuYjQK+SbA21uigPe14Eu0QhrIlzYJU5/EFbSd
            OR3v2Uv0K2Bi8Kdu1njNMGCZWBAAbBQJch3hsKVT8UKsrz1jWMhuiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T23:05:30Z"
    mac: ENC[AES256_GCM,data:z8KlON2PzG5AL0kZY5DROuqoJnCDihOsP5xjBQOEoYRsLKosOuzZXunB7diWROhsuZxVJ+OWNGpKq3vcwctwaKPWftbZEhgNRr3FkkY53mBEpTEOqoZqjDKDTPHbcdJVe02JeR3X6PqrGXu7xiO68JbyfsWiRoL/1QqeEYcF02Q=,iv:uNQtHRebFHkuJ3zJoslycmYpiiGHwxjQfFesjIfT3k4=,tag:Za1w8MgxYyR4wKipQNYujQ==,type:str]
    version: 3.13.1
