apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    secretKey: ENC[AES256_GCM,data:klDaCmT43nWJY26uyN4PLBelzyF5OBfCKgTWDuv/0lI0Jp1kie5kx4sc7/uOvC1ZsYhCMBjsOGtFXGJu+pw8Ng==,iv:QmcqnMTCg1eSdHMToxvz0IVGaIAvoopJN2DeaaQmaTc=,tag:TWwYTLl1WRvUfPA1SP7abA==,type:str]
    bootstrapPassword: ENC[AES256_GCM,data:WDhgHmfMIOhUHmGZ5cxP8hBKJgf6lQ4hLjv/sdVKNus=,iv:PAzLo1KpwryrVZ2eO976JLG+D2+CMWM9YfC+kcTMk6U=,tag:QlWvPvP4kKd3/tu0BHeuMA==,type:str]
    bootstrapToken: ENC[AES256_GCM,data:3oU14wR8v155lPnmEe3RXJ39NiPZ5v+v0kTnYDg23DD1EeYevPkH8Ruubw==,iv:qKf9XZzesyiG3aLKuO971SZJzwuoeoWXwqkroGlxAP4=,tag:imxJwRLlZzze4x6thj+nWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VzNuQ1NZOCtIeG0yTWo1
            cTZrLy9xT2FzeVVyd0JRaGU5RTRWVGUxbVJrCllpUzRzMzVRY0xjaXQvbEN3NkZP
            ODF6OXB2Y3BsNWZrbU50OFdnRllLR1UKLS0tIHNsbklWS21lVlBKTCtiMlpCZjVq
            Vmw2czMwaDlZWVkzb0xMUHNUeVpIZ3cKPr01lSGXxCVeLFVx9S/Ok0BbLSWH5P1E
            lnvQalUSmBGlqnhWct6lF3CtvVmacmGY4ZpU0hy2cyH1M7798F76Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T23:04:11Z"
    mac: ENC[AES256_GCM,data:YMv4j/Cz9uxqM8Q0ne5cSyWAbX66vGzjnim2HM20VoBZJgxvtAsQyu8D55b7nOzE+vZT+AorGHX3nVvoDJitmlho8aq+gEGchUyKoGrUmhFQ1jx5cO57ilXUPgzgv3cujtXmZgcXk44QpmVzQiowonNAA+Eg7OHpuL3xnF91uBM=,iv:ez/ZszR0HNX37a5+iHvw9OIniGqwEgv5wLeJx8lNcPw=,tag:wQKQvXO48XqQwIEzyMn5cw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:hMv2r1GUDfjXVys2L/3rEOpGO8d/tItCWnZrZPfVdfM=,iv:GAAYics3y/6ySZMTBNb1Bo0SClSgkQXwoNYlMacjE2Y=,tag:FPN3w3S+Z0O6PNM4Jp8Wcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VzNuQ1NZOCtIeG0yTWo1
            cTZrLy9xT2FzeVVyd0JRaGU5RTRWVGUxbVJrCllpUzRzMzVRY0xjaXQvbEN3NkZP
            ODF6OXB2Y3BsNWZrbU50OFdnRllLR1UKLS0tIHNsbklWS21lVlBKTCtiMlpCZjVq
            Vmw2czMwaDlZWVkzb0xMUHNUeVpIZ3cKPr01lSGXxCVeLFVx9S/Ok0BbLSWH5P1E
            lnvQalUSmBGlqnhWct6lF3CtvVmacmGY4ZpU0hy2cyH1M7798F76Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T23:04:11Z"
    mac: ENC[AES256_GCM,data:YMv4j/Cz9uxqM8Q0ne5cSyWAbX66vGzjnim2HM20VoBZJgxvtAsQyu8D55b7nOzE+vZT+AorGHX3nVvoDJitmlho8aq+gEGchUyKoGrUmhFQ1jx5cO57ilXUPgzgv3cujtXmZgcXk44QpmVzQiowonNAA+Eg7OHpuL3xnF91uBM=,iv:ez/ZszR0HNX37a5+iHvw9OIniGqwEgv5wLeJx8lNcPw=,tag:wQKQvXO48XqQwIEzyMn5cw==,type:str]
    version: 3.13.1
