apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    secretKey: ENC[AES256_GCM,data:4ndZUjlAqcoiGKWsceGJQ0GmucrSeIDK6bBQxssX0FNyMOr9fwEUDuPxuZjvJo2xVXiH0hPrL8At/5qkg6iqnQ==,iv:DGqqCSF6RnOMaxiIWpUDuecdcAEL9cSyYOKXe0Ho5B0=,tag:56gurcquuf+7tsP/VGvktA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:ZJHUN/yF27XkYeRwA8BjPa037jTS/XWLjFGyDecbeOo=,iv:lhMQT7Jmf7eHHFtbqWeu+XJNRv7heYwQFtnpSbzHSFA=,tag:IJzyS1AvjXnGUf/9c5WEwg==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:HoeLiYv9TUl890JWjRs/VXXDethNNT/xb1c9Nv1VYilw38NW1x3LVkVHEQ==,iv:mFsJJvuJURPZ3eJc4kFgnmHxc2mwG1UI1J7brZdWx6s=,tag:jWA49ZWssDdcuzNlHmieiA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:sLIZ3Mmu/OXlgjSwKhQah2JWDw==,iv:tAol3YXk0IvBZBwhwDTnONC21SkVHnUU9pwh65x6f94=,tag:3cfnPmcXusmoLv+iFQr9tA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodnhPU21pTTVZQmFUS0Nu
            aU9iZ3dUSENWYnZzZ3RnU0I4bm5UNmtvYUJRCnVNVWRydC9xc1ZJaC8yVzVCK3lw
            cmtJWWs1WGhmNjh1cmF2MWM0ZXYvZmsKLS0tIHNXM0dRQ2YwZTV1YlVMOUlOVGhE
            UXI2SEtTdlhtKzE5dnRqbGJsTWxITjAKXYfXYPIgHAJ/42/3wqkQ28tyfMZCXaxo
            N+Q9YtsJMfIZyEtB3S779Q1g6IfV9D2iZr962jGB8oMe6dmUKUsccg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T23:12:01Z"
    mac: ENC[AES256_GCM,data:Yu6tgfwW9tkiJ6z4/RT6MXWR35ALiOfnkDvTHfO45Z6DjyQKGRMOF8IwqVwEh8NHuiFt+YZokzt37U+a72Qf9DqXt/8dRPKzJnKXwNgNlCpKamB7arLCiOUMB6y5PvbZTu4GmbaSJu0D4Om9Q7KtTLr79oQiZt/SvmOSJC5V1+A=,iv:fX99T2g6Udaj9HqspcdtQMnGxYnWQgw0ETPNFZ7RLyU=,tag:G5u82q/TtL1WWUBYj5xkhg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:BSRse7KPPYduSGoWgeL4ms7e7aL6UABye3FMH8OyBr4=,iv:HHnrSZNbUsLES2Bayq4/Jn8dsD4d3HQBBf1JC+ZdrRY=,tag:jbvSb462N2n38HIsP/+LXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodnhPU21pTTVZQmFUS0Nu
            aU9iZ3dUSENWYnZzZ3RnU0I4bm5UNmtvYUJRCnVNVWRydC9xc1ZJaC8yVzVCK3lw
            cmtJWWs1WGhmNjh1cmF2MWM0ZXYvZmsKLS0tIHNXM0dRQ2YwZTV1YlVMOUlOVGhE
            UXI2SEtTdlhtKzE5dnRqbGJsTWxITjAKXYfXYPIgHAJ/42/3wqkQ28tyfMZCXaxo
            N+Q9YtsJMfIZyEtB3S779Q1g6IfV9D2iZr962jGB8oMe6dmUKUsccg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T23:12:01Z"
    mac: ENC[AES256_GCM,data:Yu6tgfwW9tkiJ6z4/RT6MXWR35ALiOfnkDvTHfO45Z6DjyQKGRMOF8IwqVwEh8NHuiFt+YZokzt37U+a72Qf9DqXt/8dRPKzJnKXwNgNlCpKamB7arLCiOUMB6y5PvbZTu4GmbaSJu0D4Om9Q7KtTLr79oQiZt/SvmOSJC5V1+A=,iv:fX99T2g6Udaj9HqspcdtQMnGxYnWQgw0ETPNFZ7RLyU=,tag:G5u82q/TtL1WWUBYj5xkhg==,type:str]
    version: 3.13.1
