apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "56.x"
  valuesFrom:
    - kind: Secret
      name: grafana-admin-secret
      valuesKey: adminPassword
      targetPath: grafana.adminPassword
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: local-selfsigned
          traefik.ingress.kubernetes.io/router.middlewares: media-authentik-servarr@kubernetescrd
        hosts:
          - grafana.home.dcxxiv.com
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.home.dcxxiv.com
    prometheus:
      prometheusSpec:
        retention: 7d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: longhorn
              resources:
                requests:
                  storage: 10Gi
