apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "56.x"
  values:
    grafana:
      adminPassword: "admin"
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
        hosts:
          - grafana.home.dcxxiv.com
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.home.dcxxiv.com
    prometheus:
      prometheusSpec:
        retention: 7d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: nfs-provisioner
              resources:
                requests:
                  storage: 10Gi
