apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:KigOu7q7wdZRw2lddjuwKib8DuXQl4IYGKZoJAI28R8=,iv:K6kXlnfRjPPJlGQ6OaEKg3UAgQ9TcQx83PL8La038CE=,tag:38K7x/4nlGTSNExWYOVOnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaUUzYjNXalZ3U3VxaTMv
            b1VNck45UlJpQ29FbVZua0NVTk5OU0hjUFY0CnE0RlFkcVhnb1BTYldPZ1BwM0hx
            RGUrRlB2bDY0cm9lOUd0b1dCNCt5N3MKLS0tIEYzK00xdzBoWUhYSjJYSkhkekM1
            NXdCYUtWajNKb3oyVFF3bklrLzlyUmMK/fqzeBtVBWzbHnW3mD1tStsChMZOMXeX
            CG5LW71j0Ter3EolzrIN6AVhGwzasapLfCo79xs8KaO3CMQq58hkpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T20:49:52Z"
    mac: ENC[AES256_GCM,data:zNX88q+vjrz8ATseeBTEP5zD2KYZX7Gdt2uMBqmnqXX4ghH5WpVM9rTZxbZ5C00TB5OeoGxtb7+7pWr7sIxIKzEiOQ3734zCVRtOvhPM7CSGJn6NCpfjsUN/uOJHLYheyFoVWmbrRYZK/+UrXgH/UHVYsZlgKn9DnQeLufSjrOE=,iv:pYBp/88afvmaSrlQqR1VvzbufBO35NXkIAPh+c4/EIo=,tag:BjXP18W6b45b1Zde85IqSg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:MNrMKk/57/CwXG3DRBm4scsGbLYnYzxdwvwudSTraTBVk8Upy0/NIwT80xcO6iehT56IzTNQEYUr0aHha/E9XBv28S8uWzaCgmRtiuhiUPPQCmxJ,iv:UUAK4wJpSdPdDDDCX28rZwMo3X4j49QFR1uGBuERw+k=,tag:IHf0A13xSxon5GThc4odqw==,type:comment]
    #ENC[AES256_GCM,data:x3zHwobs9Ada4kYuaay7nHSBH6cjAZ1JeNdrT3eTh7rg6JgdKXfh3rOOZuPKdye70QzvZa3S6FHJ0lAWKHBSZhmSIyaMZkz7wVMB81mq6g==,iv:getfGyX1oB9eD3PpSP81kRJv90EMJN4NYesiwDzAxSg=,tag:t6gjsxoKBAmahUb3YcvBAw==,type:comment]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:3AJtEnTPGg==,iv:YI+J6giqpsBfg1//keUH5pvlXQ2idyatVL9rSft8lZM=,tag:N+26w+fD5FobqbpFPh8uZw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:yC4TwiSmy7LR2YVojAzUHpcZlwSiMZO73FzPN+1GYUCAe+PpFPRnLKUFI8eIe6UkSFnjOHQtnfOySaLo9IKbyA==,iv:Fsto9lZQa1YNe4ANvvk3t7FeGQwX7zQggmkGeA0r7pA=,tag:Rj3IRoi7ihVgGKjZ3hq2pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaUUzYjNXalZ3U3VxaTMv
            b1VNck45UlJpQ29FbVZua0NVTk5OU0hjUFY0CnE0RlFkcVhnb1BTYldPZ1BwM0hx
            RGUrRlB2bDY0cm9lOUd0b1dCNCt5N3MKLS0tIEYzK00xdzBoWUhYSjJYSkhkekM1
            NXdCYUtWajNKb3oyVFF3bklrLzlyUmMK/fqzeBtVBWzbHnW3mD1tStsChMZOMXeX
            CG5LW71j0Ter3EolzrIN6AVhGwzasapLfCo79xs8KaO3CMQq58hkpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T20:49:52Z"
    mac: ENC[AES256_GCM,data:zNX88q+vjrz8ATseeBTEP5zD2KYZX7Gdt2uMBqmnqXX4ghH5WpVM9rTZxbZ5C00TB5OeoGxtb7+7pWr7sIxIKzEiOQ3734zCVRtOvhPM7CSGJn6NCpfjsUN/uOJHLYheyFoVWmbrRYZK/+UrXgH/UHVYsZlgKn9DnQeLufSjrOE=,iv:pYBp/88afvmaSrlQqR1VvzbufBO35NXkIAPh+c4/EIo=,tag:BjXP18W6b45b1Zde85IqSg==,type:str]
    version: 3.13.1
