apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:qoMlTOZ1XYjVVyzjeWJ1ICghrgMDOa2OW6OrdZDfI6FXPbIz9I0B9oPfzw==,iv:0NRNEI6aYATke7N1DNK+CKu4a/3Je6/VWgAompI/0zU=,tag:XpIPfb+MWbvEbjXs95pW/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaUUzYjNXalZ3U3VxaTMv
            b1VNck45UlJpQ29FbVZua0NVTk5OU0hjUFY0CnE0RlFkcVhnb1BTYldPZ1BwM0hx
            RGUrRlB2bDY0cm9lOUd0b1dCNCt5N3MKLS0tIEYzK00xdzBoWUhYSjJYSkhkekM1
            NXdCYUtWajNKb3oyVFF3bklrLzlyUmMK/fqzeBtVBWzbHnW3mD1tStsChMZOMXeX
            CG5LW71j0Ter3EolzrIN6AVhGwzasapLfCo79xs8KaO3CMQq58hkpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T23:34:32Z"
    mac: ENC[AES256_GCM,data:5EbE197dNNQ82Ttdtk6696qq8z6novNSoZczKiGKjtgTdJYy65ZSIVhWa9+P1uXfYmYYhL4ZTDtj7xty7RpE39GHlW2U+Mf/rEYyef0W3mwme8fg8l7Q7Pq3Jm5qaG+Oc2fuGqnUQp+uGkGbatz+c252tQj01MnNLAwX2plB0WE=,iv:w/ES8Yig7rkl3i/3ahsN1J/jqBQc6UhCve1ZOLe9bmc=,tag:rdWbgzOaD7U4D9hdUatK8g==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:n73aj1vtpxg7tBp7x1uoD3q5EMj0jSPbEYMevTXSjApCpkKdIXxqQXD7DdMpaMv9Bsxdyp88a1JCkzj8wcTfn3Z5QbokPAG1uQ==,iv:BzZ7WOc6F+RuPnB/RGVhz0/B3GIK/UEkbz8PbWEuKVU=,tag:ASO/0G6pc1aiEWDqvBK1bg==,type:comment]
    #ENC[AES256_GCM,data:o1JHNu8i7Ii2Axk9ZYLO/608gHR51t9V7pDkNBfpvP9iYa6HHeLWb0xjoU/srwnTyrBbywoflNqIUinlhktRKuKXw0oG+H9wnwDFw8yNAwrDLnIhfn889WGC7N0uejM1ni4=,iv:CcEmeb9+lrgrffT5Mdx5nqHiwWHfym3+z+hXQ8HkGPk=,tag:MpWs9B5qmiDjiB7gbwR/jQ==,type:comment]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:IgHM2EcYVtO/Jmc0pHCDpm0M4nIMuOpH70gyWmkvGsbRm+M=,iv:uFPC2DZuQqNLKJhUk9RU1ccIl4mg2m3Tl/lxOhNreAY=,tag:FoSUfzWtGRY5IQziyFkN9A==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:cslJBYoC4WicShBDd7fIFyyhBnmKYfFDG1v3GoJVbGspFyY=,iv:rp773gGaYsuunJAaGodfhRluPeB3Z4zCWEclpq0Xuv4=,tag:1AkQ7GSlEWK/LSjoU4mlgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaUUzYjNXalZ3U3VxaTMv
            b1VNck45UlJpQ29FbVZua0NVTk5OU0hjUFY0CnE0RlFkcVhnb1BTYldPZ1BwM0hx
            RGUrRlB2bDY0cm9lOUd0b1dCNCt5N3MKLS0tIEYzK00xdzBoWUhYSjJYSkhkekM1
            NXdCYUtWajNKb3oyVFF3bklrLzlyUmMK/fqzeBtVBWzbHnW3mD1tStsChMZOMXeX
            CG5LW71j0Ter3EolzrIN6AVhGwzasapLfCo79xs8KaO3CMQq58hkpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T23:34:32Z"
    mac: ENC[AES256_GCM,data:5EbE197dNNQ82Ttdtk6696qq8z6novNSoZczKiGKjtgTdJYy65ZSIVhWa9+P1uXfYmYYhL4ZTDtj7xty7RpE39GHlW2U+Mf/rEYyef0W3mwme8fg8l7Q7Pq3Jm5qaG+Oc2fuGqnUQp+uGkGbatz+c252tQj01MnNLAwX2plB0WE=,iv:w/ES8Yig7rkl3i/3ahsN1J/jqBQc6UhCve1ZOLe9bmc=,tag:rdWbgzOaD7U4D9hdUatK8g==,type:str]
    version: 3.13.1
