apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    home.dcxxiv.com:53 {
        kubernetes home.dcxxiv.com {
            pods insecure
            fallthrough
        }
    }

    .:53 {
        errors
        health
        ready

        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }

        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
