apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paseo-cert
  namespace: paseo
spec:
  secretName: paseo-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - paseo.dcxxiv.com
