apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paseo-home
  namespace: paseo
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
