apiVersion: v1
kind: Secret
metadata:
    name: paseo-secrets
    namespace: paseo
type: Opaque
stringData:
    PASEO_PASSWORD: ENC[AES256_GCM,data:J9bQnxoDdbqfPGtRGPXTfU9PUR4+yvMEvjCt0gMf,iv:WiXWaE++1y4PeTcb1lHY+YxrZdxzA+2P+TNK7Sfztfo=,tag:kLLsn32TOqUZ6TNKm43NQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSkJkMWhRMUM5REZ2NnND
            blhlYnR0NlVRMVJtMzR0RFNwam9mVWZHOGcwCmFFMzgrUGoyNll0V1QvNE5LQ3Vx
            NS95ci9Kb2hZMDdYWWhYdHJYT1M2Mk0KLS0tIDJ3VG9pTmJKSWVlcU5SYzdzRnFa
            Z1N4czN3aVlhWjZmMEFUS0ZGd2VrcFEKlDzs9mErP/Ii/NKw7fg6q+Cf4aZuSl8Z
            /gH0mnM75bihI9gWi3C+xBfP9/srf2dfGvm4+q6da/K1rTi4b3b26w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T17:35:55Z"
    mac: ENC[AES256_GCM,data:7hABrejg92vVi3mWSF/RFAZGtVmzn/A/KrmGQ56z47pZ67EVr+E4NRSUI5sgjNt11vQcELko0NIUxp++FU6c9rROtpRVNA4m2LyP8cnw8X8C4Ky3aUCpKwyqfHe1w1FFXzmUISE13RQz88BzY31K96v+H349qtfgRCRmuH4MkQM=,iv:6oSF4ubftX9JZ3cXf+TdOEWIpzkHvqLwGHtqSLmrAtw=,tag:GRGIo+k0pGLoQQv8VOhYHQ==,type:str]
    version: 3.13.3
