apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodecast-tv-data
  namespace: nodecast-tv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
