apiVersion: v1
kind: Secret
metadata:
    name: nodecast-tv-env
    namespace: nodecast-tv
stringData:
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:xCRiE1/To/ntEbt59lIwF10ytar+EIpwHOEKhwG4rFT4Q1vv/sZzjWEC+Yvuv9kuy3I=,iv:yoPIq0BWE+Ztj0KG9wiSjV1lhWbOZ+sKyxYz6g47e3E=,tag:AIqE0Z9gPMfV0izfZCGfiw==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:Egz/7fDXE1dBnWw=,iv:K5qWEsHRp/O0rlJJZ4cTIw3oAo6VX51sNkVOgVUEJmM=,tag:cuLda7pyWXZ6Ru8FQYOgmQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:MayIBr0wUQXbF8jcCAf62jFlczohvYXfW36RxaEpLPJsYHBtzoapyTnhhIbEGcSwcCFJ1Gvb18ggYXtADLdHPQ==,iv:U5T6s4ADthnAjuHVGxns+jiPULSWxLXuhiqIWYQi1R0=,tag:Eu5X0HN1uGoltNmz0fKEtA==,type:str]
    OIDC_CALLBACK_URL: ENC[AES256_GCM,data:RxX/kTlfRIipMBp3RcnoWOENDtWZ6xqynxV2q+0seqXDc0PbfvoSM4bdnTQ=,iv:FLaBm7ob1drp62rbvkUprca/UWSC279SwL+2mE9A9m8=,tag:6sqBlqRhvga9Pv0VNIAL2A==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:f6tiDCjKH+4ySbsQ2zGyOK/cq0+iNsa4Pfjj93r3eq6vG9Tze70Im/ArFYNZV4aNEJEvK1Ixuxy6sBgiBt2OgQ==,iv:wUCpK1ZVvP5ECpLH4alZrzgRZDNDim1pW0mIwwEoDOo=,tag:ZK6tyPOyPBPFRTw0qT0NCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N2NsYjZSZmNHTXhqU1dG
            K3hjdHZRVkFwaEg1THBvOG5PSXVUTnJGQzE4CmlpV2FqTHVQM0lkRFVUNGtuekNT
            OHZhUXJkclpqNmlYdEF0OEpaYnNndjQKLS0tIGN4QzA0U3JEL1F5YnIrcytwakQ5
            ekN1dFprSVBRVzFMSlFhRUJ5TlNpRTAKAQbfN/kjrxv7v46rWOYLZyKN2GfQjAZE
            mAhOynlrzio8hWK5nRja29Gp0TsFbFdnd7hDNjK3W5+WjlDbTeapnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T19:42:59Z"
    mac: ENC[AES256_GCM,data:qA7BUjjQRbhhpb3ONLW8L18DZEwcXEvOFo64hfja2yKMrVcNYYEEEVmCMCZtCBgp5JL8oOOW1NjP4ukaVhgB+L8ns92yhFNphX4V9hxdEJxwPTEtpFn8Np6+6R/qmar50mC+BSkHyqceAlk3m7cvLAs3KovfkMNU+Xn8BCS7fUY=,iv:V5NyZeOaeDrJ6sZRSHxBECx+tKNmUxwQiUseGNZQMg4=,tag:GTdD+GQaC2SlnH7BSjpBSw==,type:str]
    version: 3.13.1
