apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-jellyseerr-config-pv
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/jellyseerr/config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config-pvc
  namespace: media
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: local-jellyseerr-config-pv
  storageClassName: local-path
