apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellyseerr
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/fallenbagel/jellyseerr
  version: 2.6.1
