apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: jellyseerr-jellyseerr-chart
              spec:
                template:
                  spec:
                    dnsConfig:
                      options:
                        - name: ndots
                          value: "1"
  interval: 5m
  chart:
    spec:
      chart: jellyseerr-chart
      sourceRef:
        kind: HelmRepository
        name: jellyseerr
        namespace: flux-system
      version: 2.6.1
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values: ["k3s01"]
    tolerations: []        # leave empty unless you’ve tainted k3s01
    nodeSelector: {}       # don’t rely on labels; hostname affinity is enough
    service:
      type: ClusterIP
    config:
      persistence:
        enabled: false
    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyseerr-config
    ingress:
      enabled: false
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: jellyseerr.home.dcxxiv.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyseerr.home.dcxxiv.com
          secretName: jellyseerr-tls
