apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: jellyseerr-jellyseerr-chart
              spec:
                template:
                  spec:
                    dnsConfig:
                      options:
                        - name: ndots
                          value: "1"
  interval: 5m
  chart:
    spec:
      chart: jellyseerr-chart
      sourceRef:
        kind: HelmRepository
        name: jellyseerr
        namespace: flux-system
      version: 2.6.1
  values:
    service:
      type: ClusterIP
    config:
      persistence:
        enabled: true
        claimName: jellyseerr-config-root-pvc
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
      hosts:
        - host: jellyseerr.home.dcxxiv.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - jellyseerr.home.dcxxiv.com
          secretName: jellyseerr-tls
