apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository-juicefs.yaml
  - helmrelease-juicefs.yaml
  - secret-juicefs-aws.yaml
  - pvc-juicefs-meta-longhorn.yaml
  - storageclass-juicefs.yaml
  - pvc-example-juicefs-app.yaml
