apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-meta-pvc
  namespace: kube-system
  labels:
    app.kubernetes.io/name: juicefs
    app.kubernetes.io/component: meta
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
