apiVersion: v1
kind: Secret
metadata:
    name: juicefs-secret
    namespace: kube-system
    labels:
        app.kubernetes.io/name: juicefs
        app.kubernetes.io/component: backend-secret
        juicefs.com/validate-secret: "true"
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:PST1RbR5OrCQWRSLag==,iv:xHV6kvnyx+emI1j9T/4G3VeJZ7cmqgGNTY2ysiSa73U=,tag:rT/KnONxvwXaLTieO1SIiA==,type:str]
    metaurl: ENC[AES256_GCM,data:G+aRkJvZt8eSRCJDNCvLyKvt6mHH1fbyRrm8gDVzVWgkwuEV6bqH/IVMdm9tIDScQBrqwZP03+dvRJFBmikWCvs=,iv:u1U9xkotPN8AeUe1LhRBCudkB5i59ql7tdXJ7qTEAS0=,tag:waN8+KE9yWxnHRlcmB3U8g==,type:str]
    storage: ENC[AES256_GCM,data:fdE=,iv:FFFeAFTfQymfTO0gW6MFwKtMQXTqnmHCLsLcosHbqDQ=,tag:Rh69rtWkUFPFP2bAmeIRZw==,type:str]
    bucket: ENC[AES256_GCM,data:MaIkAvSkq1I3duLMXvXPbHtSgV0=,iv:cnCHtYhrlZyJD1xduol4vppIQk39lzoyiNpiU5CVyRU=,tag:KI3d144REvGbiXs3jfg/Cw==,type:str]
    region: ENC[AES256_GCM,data:MjYa+EIVNloQ,iv:cqG5d4SFM1cITJVWkCELQkRdDByZtweJc5rKx6wjXFo=,tag:laukeU/Vv18iCyaHVhAoAg==,type:str]
    #ENC[AES256_GCM,data:6TdeL63N6IbHOVxmYV7y5VZiv2u74+axpVklZtITIIssyPxDzElbyDLEKN0n,iv:8HdoXQprCqB2aIWmfgMN+8LtcdZN2qJaaU0Pj6ltFBU=,tag:tHXbc4LxsyS5S9HqwrVUgQ==,type:comment]
    access-key: ENC[AES256_GCM,data:1EwB2oFj+w+GkXmWpjeNKQnQFnQUNY1X9w==,iv:PyWa7aDZFpGNn59SgtVUJwRdECPqVja+7kg86xliVzE=,tag:+1zx9w/lFsqzq9jZ87G4TQ==,type:str]
    secret-key: ENC[AES256_GCM,data:03TSvSnDEEtPZ2aK2qSE/8gLnncL0tDc3rbPYts=,iv:7hbFOgLxaCuAKCg0PRG7qam9fzjcpQX9BYv1pVgoD40=,tag:/IsVH7GOvuzSbRYLpxacCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSkJRSXdYU2RwYi9vcGI4
            M0NVZkVESVl0Q2gvd0crTFZwejlyelF3NlJ3CnZ1aUVjWG9OOGpVc0MvWVhUbUp5
            MEtoWTBmZzNGWkdTTmNwMUg0U2dsRVUKLS0tIGxEQlN4N1kzcUZRMWlzNjBGb2Yv
            OHlVdEkxd2c2NW0wMWZKYUdEYm5aUkkK2wq5gmtmC+EriLV3WhDeqnrCA0mSXvlz
            x5gMVSFiMYeM4aeCB8Rzz6Ne6yo0cbtCvl6M0eZYpHB9eR10GUVKZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T23:34:32Z"
    mac: ENC[AES256_GCM,data:WOZsyZny1KRiDFAvqAGdUqPcoi6TKTm/xgNHjG7KBpv8knZFOp8WV1/rkC+TorNeScnMP9j+Fw9CC4dYkbj31qASD13UfZhVfUNV/L/3S3fTTjCpgf0thu9PRzXmcMVidI3TkDQz3R4ijeOdh9zFwPz9Eq3qeVrfBuUzBOP6YTM=,iv:ZThzl/sj4Zjjc5U7s4MUUCMARY4wXEACGPiwujunLIE=,tag:UkJC3nRB8JqjHEc3u0/7sw==,type:str]
    version: 3.13.1
