apiVersion: v1
kind: Secret
metadata:
    name: juicefs-secret
    namespace: kube-system
    labels:
        app.kubernetes.io/name: juicefs
        app.kubernetes.io/component: backend-secret
        juicefs.com/validate-secret: "true"
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:DB2MkWABr8mpFfB/uA==,iv:PYJaeuF3hG5hpkHuMvvLRr//HbFa5ItzmX5FIOqwbE4=,tag:mL1Ci/PMOPAbrwIPVw2oDg==,type:str]
    metaurl: ENC[AES256_GCM,data:9F6SVjygck7MUEnth4v1T+LiOc5xtBsOXEnVlJjQ7x1l5SJFO40a1JCaRcfHvEpwvyUJqBbSNzAsrhkuwACXXKToVmGuOk/fHEIO/cNQGD7J5i2SdDPUGmXvdFLWl6oofCoDHHsrs+Y+zio=,iv:ZOS2NIoobRTWQu2q+VOgLx+xHmKqvNERPzLL4Rr6Bz4=,tag:gMaMyHRLjjH9HeFRWsIACA==,type:str]
    storage: ENC[AES256_GCM,data:YoE=,iv:Eb9avT0i8hpKeNnydHhG6cYJsOdfHYpg8ariShhq4kY=,tag:3B8gOVmG/v+abIuomtNV1w==,type:str]
    bucket: ENC[AES256_GCM,data:vrnGcq5DCtaK8UZfuzdqp3w/Duc=,iv:xRXjWjJKSnqnN5J7Qz6Y1lRU4/8y5NS/cHeorfwhBrk=,tag:DEoiBamtDaXE3J2s6XSmkA==,type:str]
    region: ENC[AES256_GCM,data:jrvvjd7qEPgK,iv:Hohsioodk26i1onn/W5SHpJUnjQ5kNIalKNBELPXVWU=,tag:4MyYDuARjIw6YeD0ofsb7g==,type:str]
    #ENC[AES256_GCM,data:gshRb1CAPxjrc9dkNYIHIPGw/+n/YbEBi57d0pU7PrFGgPCs2AIG4vF4hQtZ,iv:Uu8ASzJ/eViYPjhAkR3CjvriSSWFPYpOAckzNPsPqVs=,tag:qcSPDsSwG2prf7KcegJ/KQ==,type:comment]
    access-key: ENC[AES256_GCM,data:QyrYtZmiWa0gYWwditbLdMiPvGw=,iv:de6+iARH0R/DJ9sutukrwgKg1Mkv0m67NFfVwMzWi/E=,tag:/yQxcDBjO9lZ3zM+EZY8yA==,type:str]
    secret-key: ENC[AES256_GCM,data:lrqAYfEAzOMpUM2+JLijFZ7xMMaH+iYqVxcueFmlxZbtR5/2onPRQA==,iv:r+RQrykKh0FHzNBBJCeY9gBrEGn/sdxqafK6ydZTS40=,tag:p/fIIWjMROaEwhsmdl8JNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM1RIdFk1dkY0c3htVTNm
            MENlb1hONXR0SFlYTDQrOCt0aFpoWXFqc2d3Cm10ajI0Q2tJbkIvUm9PTFhWUzl2
            cElOeUt4K3M1YlUwQStaY1VVTVRsMUkKLS0tIDc0bXNNdjFzTFdhRVN3TFVYN1Bl
            OHpiNlV1VmpmTWF3d0xLWWRBckFyYW8KecJIw1oacYNJ9rcmgWgUV+C5N8LKxhGj
            73BwYH7fLTmttNpklFBXVapfn3i1zjyNbZ9A/mGtX86iaxJ/Qf3uTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T17:21:10Z"
    mac: ENC[AES256_GCM,data:5nFU7xa3wRfV+oy28WnfjlikkMkhlK1O7vfpv3jA2opRCAb6D6Inr4k/tBCHAqwFCpUx6YCeYDcS+fYdG650khVIP6SP7mI98FM7PbTXPrkgcmDNmA0EHreBpjVqTkoKBXNII9qhM6XARKVMGj1GPIQBOiSAHaANVSGIaQOtHns=,iv:EQH2xjRwvUCs8G7/5MKIg7Qn4Sm3UOeIHzzxxoiz1Io=,tag:6ZDpi3jjqq0mAX/1/iOhyQ==,type:str]
    version: 3.13.1
