apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: kube-system
  labels:
    app.kubernetes.io/name: juicefs
    app.kubernetes.io/component: backend-secret
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: <JUICEFS_VOLUME_NAME>
  metaurl: sqlite3:///var/lib/juicefs/meta.db
  storage: s3
  bucket: <S3_BUCKET_NAME>
  access-key: <AWS_ACCESS_KEY_ID>
  secret-key: <AWS_SECRET_ACCESS_KEY>
  region: <AWS_REGION>
  # Optional: additional options during format
  # format-options: trash-days=1
