apiVersion: v1
kind: Secret
metadata:
    name: juicefs-secret
    namespace: kube-system
    labels:
        app.kubernetes.io/name: juicefs
        app.kubernetes.io/component: backend-secret
        juicefs.com/validate-secret: "true"
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:5gp381pJ3h6v05llbg==,iv:e5prIywa79auXu4Ts9xg5HvP2F037+8H7JakmKin3n8=,tag:SLK9r9X7DwzORfQcuAG1eg==,type:str]
    metaurl: ENC[AES256_GCM,data:fPzf7CrPkqlbRk6QiiUiKch4JOaLJd2fbs1QcD1RD7s4a9yI60hWeTH1QwY//orEJdtcUytIlL15GEzP3Kz3HTK4J+nr8t6IVxoFxmpqvHMVEt9fsQdegVMC4Cevvj89Gg==,iv:hEVLn5YMoIYY8g/OA0gAYzmKK2UqV8ZFrWz977VsmJA=,tag:dKSVKK7XvWoXATMT/AkoSg==,type:str]
    storage: ENC[AES256_GCM,data:SfM=,iv:8rfj5/Avx37+kTTd2z2LhEwnomNoxDgroq5DAp74XXI=,tag:Z60m6KsyKNuPbml97EK0hg==,type:str]
    bucket: ENC[AES256_GCM,data:IdIauC3l2ODjYLxc7QQlYx44ChI=,iv:bu4ty1+jZ2MSGz/WwyTu7srys2BsMQBTkeT9hqESOhc=,tag:gH2blYJkXIvAplW2vGe79Q==,type:str]
    region: ENC[AES256_GCM,data:wc/wNtP5cUWm,iv:cuZrVA3/TVXKKwgBX3Yam61RmauOF+1z3BwwYU+G+Kc=,tag:ulUotS0Qsg5w5RmTGKyuDA==,type:str]
    access-key: ENC[AES256_GCM,data:EPOMaWbOVieMqm8SX8f2jfQIpqk=,iv:7fvI2IsqHWeX+6G/7AuUahwZSiLCinLQLLOBydtn6pk=,tag:lCptiOGFRdnhz6xSi3ijmA==,type:str]
    secret-key: ENC[AES256_GCM,data:PbdnHyknfIxqItBE/sz52oMyGYYwumWNVL862VnLYfNPKU4dxPVi2A==,iv:X34Gut7uGzslH+xkATf5bAA1SfQ9t/ANcwtvM5yQPcw=,tag:Udwwz1BG8e1D9o7EXCV6qQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRjdSUG14QVJHRUxpOFVD
            QVpDU1NXZzNaNEpGMi8rWm8xSU9VM3dQREg4CnNzemVrZDl5VHZNM09oVFM1THI5
            b3YxR05GL0o5Rmx2Q1dqSHc5cm9nWFkKLS0tIHo4R0pROG5NWE9obGN5b0R2emFv
            V05DZHFwanVmSzl3R2JNcGhLOVJ0N1kKYjGUELl0D8z62Xc/hW/YxlJoFJ6FKvml
            PbUKK8RJnkMDRVxBxJP4sG1rgpHSM3CUwaJPMq0n37pRlkR54TwhVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T23:13:26Z"
    mac: ENC[AES256_GCM,data:aS9R8gjn+qCjvlaipT6mqxJcE+/5XgoytI1x0YiHcsg8h0hypqbMsaDCLuljlNHOXgw6bYQsPuoTQdvzMefqs/sYAXMiB5+40M6FSF9AetDxFkZzXlAdnaqEr/Ie5vV1vHcIYJmB1ktWGAKLasKtp495omJxqHssKWxae6+soMc=,iv:LFnUx1qKkv+fFEQ/ZRjxwNhAef31eZrELJcomKvQ4og=,tag:UM72fLhU0ZW6eI07WDEUsg==,type:str]
    version: 3.13.1
