apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: kube-system
  labels:
    app.kubernetes.io/name: juicefs
    app.kubernetes.io/component: backend-secret
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: juicefs-media
  metaurl: redis://juicefs-redis-master.kube-system.svc.cluster.local:6379/2
  storage: s3
  bucket: juicefs-media-bucket
  access-key: "" # put your real access key here
  secret-key: "" # put your real secret key here
  region: us-west-2
  # Optional: additional options during format
  # format-options: trash-days=1
