apiVersion: v1
kind: Secret
metadata:
    name: authentik-role-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8Aa7aoGKAMbk,iv:GmnAOyFlDuD8ogy72pAz9yqdA2cz8XwCHjA0+1hEYH0=,tag:1fYjlOOSlJdkkEZ6kpFTCw==,type:str]
    password: ENC[AES256_GCM,data:AZNJFxXKKImLlaGFLpgHz/QPEK9gQedNO+WhqTTWdGw=,iv:PkG9AsnvjnluzH36MnZga/LkZ15ptebLBvwwZx010pU=,tag:YJTZt3V0Vm/2F988MdTA+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeWNkTHJJbmFvVE4wUHVv
            SEg0MWtFb256bDFIZ0M4emhGMmJVdjR4VlY0Cnl3L1dHcU4zdWJpOUJYRXhNZnIz
            TENEeWtuck10ZHFqWEx1a3F4Rjd4V28KLS0tIGViQ1VpUkgvL21JTUVLNS9QVHNk
            NTJVa3RRQjRvdjdmQXo1c2UyaEV3dVEKkwqEb3d5pusE/n9J1NnVIOnAqMMw+2/X
            +6BPfDAZcsBQl0QfwSp7QWFrLDK5OUgkSqh2+3zxtwiyzd+SwRdJzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T23:31:13Z"
    mac: ENC[AES256_GCM,data:AWZfVSeMoN7+GjC2LSyUc5cECVYo9fqODDMsUbuHUlJDVYPUfU81/i5Gc05FMeqwJBZpBDjSERedU54cq7KFkQ9W/xUc2vjhOP1Y142JPOl9vaVgP0IdUZTJJ7eB2p62pFzOOfr13viEmKfoD5hOeF4vH8qAY23YNwdnYF9+wm8=,iv:ZmouYW3NClTocfKTL23dcZADhC8N9B3dh5GvuVWSapg=,tag:jkd1fDe27lIUQrUZg2BwGQ==,type:str]
    version: 3.13.1
