apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - s3-backup-creds.sops.yaml
  - personliness-role-secret.sops.yaml
  - authentik-role-secret.sops.yaml
  - bosnia-role-secret.sops.yaml
  - cluster.yaml
