apiVersion: v1
kind: Secret
metadata:
    name: paperclip-ro-role-secret
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:18XmqNoKDf1ZE7Fg,iv:QFhpEzP5aZF7SyfZa6sw7JiDu2FFedfOWDdpkiJv+go=,tag:Lr9P+rHXDqNZgdvEt/P4XQ==,type:str]
    password: ENC[AES256_GCM,data:2V8IBzqqHS/r9d8UMf/ia5zQTYEsJRgC15dSs2twXWk=,iv:vt4mbseDhbvdlQFH7N2UVCzdTudBVt9IuxZ7cBfpz8I=,tag:y78jm1H99c0Naf5xQuCgfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieitZc0pLb25QU1prZW9F
            bk1aMzk3TGY4bks2UUp5dkV1YkVCN1lYd1ZrCkZHRnJhS2kvUXFlN3pwdnpFbWhH
            dEFlQzN2OWhKcHcwUXR6b3B3RlJzUDAKLS0tIDc4Qk14WG1ZSk44d3g2NWZGcUJv
            ZnZWaWhSNG53WllUMnc2OGZvbXh2NGMK42fHbMgbE4UpU4Q+kzmnZd1wpSb2Nfyv
            GwwPNUGCcN4SFpRzHT+aPmLJSw7ydbzseMMCyxUGOVs+HbEwCI0UIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T17:17:37Z"
    mac: ENC[AES256_GCM,data:6s5JXUxX9NNuLSAQWnUnglo6H2U8QteILyWMR/ZDGyqWwTITh9RDUg4EajO7Q5YWAInD69Ah0kxn7dH7TNq1Yq3KWG1yyRzmCNN/2GLPi0CYV82voFskZHNB+2sZZK5/PMMYy1NYi7sIvYtLWFatLI1shxWy1pDRgQ95zCbz8ug=,iv:PjrfSYEamk969CrShoWg1G8GKAUKY6jFRrqHugVufbM=,tag:D5r21sbci3+SuMW5GbUoTQ==,type:str]
    version: 3.13.3
