apiVersion: v1
kind: Secret
metadata:
    name: paperclip-role-secret
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:xOlkFDdVINBZ,iv:scB5xmulq3ykDb+bb1/W6amOb9/8a3o56qgIWPEQAa4=,tag:FaClGPEqTvyFa/1WQIOkzA==,type:str]
    password: ENC[AES256_GCM,data:7d/ZJqaWqM7Gl/XEaRAb7/EIRhr4WCZOvjnohZ0VO4K8R99qU+VaXFAnkHgjhBlKXnWE4N2pXBKnGpaIkySAXw==,iv:+rX5/JOAZwP3AgnMVc3R18fYVEQVd7tNE8WeEiWGqCg=,tag:xBEV+mg1hUz28lCzUjZMZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSHNlQTN0S2JXZDYwc3ZK
            Z3g1NHBNOGJyN2U5b2p5Mi9MUWI2R204SG1VCjJMNDRoN1ZxdkpPTXdkNFcwMlhk
            UjNwMi9JdUxTUXJqNlVNWTRBWjhob28KLS0tIERabEs1UWh5eEl4VW1wYXh5bmRL
            eHdPeCs1ai9rY1AxaTJ4SUtrWUZqZTAKIgMs+K0TnubUFXZGVc+7c7CWnZ0QzGBo
            ewRhcbmjy49cU7TOiAcZOeW9e1Fu1BUK0l3rTvy++qxBtdrlLluitg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T23:45:23Z"
    mac: ENC[AES256_GCM,data:wMKjcP+YM1h9zxNb4A6HLUnmx697P8CPQ/DQu4GAc81Lhz3i5XEfM4rvJo0fA3yeXF7sXi9Y3NwVx0qIsv4hYFvgiu9YNHKlOwKz4lrxbAA520RfCpkDmnYOau/u1DgpUiadAXQfidj6mXxFjKmZ7YctJ+62GUxVIaiRVTRrHXs=,iv:mO7GdPJVEla5kK4DGPBI9czyY8QGbl9/BDwN12xUYmg=,tag:X1HG8vtD/oHmLij6kZHnDg==,type:str]
    version: 3.13.3
