apiVersion: v1
kind: Secret
metadata:
    name: personliness-role-secret
    namespace: postgres
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:8SwFWMPQ3FPpiW7qxcq5/P80frk6g2T/y2S0VKSJj2E=,iv:uGxEjRJqR9awD3eOrkASWx6oU7HoIiELwQd6BQEEKzI=,tag:IGvzbOtb2dJzA8EXlsGLzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVlh3YURWQjRzVlVNNmIy
            WkhpYjVEOXNDeUlyeldaa1ZXVXN1Mm8yaUhvCnhMWUYxNWs4NkFubS9Zb1JjRHl4
            c2NxY0NZbHZWRmFxZXNieUJnRGlLdHcKLS0tIE52ai9COFVCMWNXcTMzaEtZSnNT
            YlFKRkJoWlBXekczcEEyb0hFVG45MVEKbeNf6cW2NB9EGvClnzL8Z+mwgZkE/kzW
            0vn8ZsCeNqeU5zLg4p8Y/4KM+uyzQd1LKCQZf/cvPQ51icPIQOk5BQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T18:18:59Z"
    mac: ENC[AES256_GCM,data:7ITEKqZeDbNwlhNCdUO/V0JSWNoLU4rjLkSJyJJOY4gbDpgm4+CRllBoPZWdpxtDEHIhKtpvkTImT9s/lEFe29KtLDylc+DSHnbXZ9HIxE6nPDqE5a+71K/shSy8+QXgdEMRttRNHOTr9C8xQhWfk1Cg/to+/8/jgrSSHQ/mxSg=,iv:/Rw3J/tUSCAs/zFoJLfS5SU0XzYE22iB9hozAYHj2XI=,tag:sybNT8tITZ6qNqcTaaRSSA==,type:str]
    version: 3.13.1
