apiVersion: v1
kind: Secret
metadata:
    name: personliness-role-secret
    namespace: postgres
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:8SwFWMPQ3FPpiW7qxcq5/P80frk6g2T/y2S0VKSJj2E=,iv:uGxEjRJqR9awD3eOrkASWx6oU7HoIiELwQd6BQEEKzI=,tag:IGvzbOtb2dJzA8EXlsGLzA==,type:str]
    username: ENC[AES256_GCM,data:lCt2zVnB1S9BhXSz,iv:MyXltIOi+JKT5iQc7SeWPXVeMzn6NDp2Y3ifCeUTznI=,tag:yN1LKqLyB1CsLm7L+eLtVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVlh3YURWQjRzVlVNNmIy
            WkhpYjVEOXNDeUlyeldaa1ZXVXN1Mm8yaUhvCnhMWUYxNWs4NkFubS9Zb1JjRHl4
            c2NxY0NZbHZWRmFxZXNieUJnRGlLdHcKLS0tIE52ai9COFVCMWNXcTMzaEtZSnNT
            YlFKRkJoWlBXekczcEEyb0hFVG45MVEKbeNf6cW2NB9EGvClnzL8Z+mwgZkE/kzW
            0vn8ZsCeNqeU5zLg4p8Y/4KM+uyzQd1LKCQZf/cvPQ51icPIQOk5BQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T18:40:23Z"
    mac: ENC[AES256_GCM,data:cA2hvg2CYeVlbP4h8uhJxR7aH5fQ/wCS8mMFAI9M2Lqzu4Y8IF9KKjOZMaLny9yyLxbV5ck1brOzFsAArUcHdIDXGR2tg8iMRH/aZuSLwX76N2IIKqoHxuruaodgko9ljKNnqf593fxL/xwg/E9rF+ff/0ll3UEmxadID+J84yI=,iv:e15zwbfwiQCpwWQ7bTgMLHsbyL6ae3ad6+xb1Y3/ZWI=,tag:MPow7hdV3yGrU3VTW/IKrg==,type:str]
    version: 3.13.1
