apiVersion: v1
kind: Secret
metadata:
    name: strange-company-role-secret
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:gEjRoP//ZFIDU2GOe6oS,iv:oDd3JhLjkUxOZZuzi6POt1Uyj0RAeoslpJcyczeqMVw=,tag:kyPoSUnI9E8X4yygtHhfSQ==,type:str]
    password: ENC[AES256_GCM,data:XdolpcPdFprSKbvD8qQabfrrAQgaRG32R1HiljqA+FqLukmwi40EbA==,iv:LuHvVtOjFH4hZDflPuzpSRgI+A4iM8E1ftwruC/7u9M=,tag:oTI/cPe/Cj//Mbrl1ivV3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOXc3Qmg4UGRQNTQ4UWc3
            ODU0S0VKUjN5TUtjWk8xaXA1blJFdjg2SUMwCjFLS3NZN05ac2NQNXJtd1MyQi9l
            TFFOYUVDanNFWHdqYVZUbjBUb1RWVjAKLS0tIGZPUXVNR05jV1ZXWWU5V0Jmc2l6
            OFNXVTJ6bTYxMVdzcmRrT1F1UmpJSG8KMlLquDXYFCuSv2lUBhM4KpZLKarw5bzZ
            JVriobZiDdbJkWavKC5CICOTsYi+dm+2Bm1VrndaCzNDfuPKN2ljyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T01:07:42Z"
    mac: ENC[AES256_GCM,data:4eeqAIFw9tj3C18NFS95RsLhUlDyt+Nr0JMXeAyHgNJEcYAxbhI+dhVE5WlS3uweN2v31ytbS+PJcWSJI4CZN0IXk3lg7yOYG4AdtWA+KfzEVictkMPIjsf6WpxAXGU/d2wD2f6W3/TXURWNAo1TTb1yjVSkDV2KYZW1qw0fBGo=,iv:1jgvmii8odZWoN22F1uxoopyFPldYqAIAnIvClD1yvc=,tag:ou5PEjGvp/UjFgGs8yZXgw==,type:str]
    version: 3.13.3
