apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deluge-cert
  namespace: media
spec:
  secretName: deluge-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - deluge.home.dcxxiv.com
