apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: deluge
  namespace: media
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`deluge.home.dcxxiv.com`)
      middlewares:
        - name: authentik
      services:
        - name: deluge
          port: 8112

  tls:
    secretName: deluge-tls