apiVersion: v1
kind: Secret
metadata:
    name: deluge-vpn-env
    namespace: media
type: Opaque
stringData:
    #ENC[AES256_GCM,data:e7vUOrlZZc+W9qPcF1Uoz9OqoMV3zdWpg7hYUO61EwiykdL2INafFI6H/jH4+TOVI2AD3MpthMbTDVccWjaJ+VrTjClArwo9l2f67UNt7w==,iv:kLQUkRtY86IQP4xqUjeHiBbEPb9Mt0ffpaGk4XM8jqo=,tag:RYHTqB9PfvmFUOkTpiQq4w==,type:comment]
    #ENC[AES256_GCM,data:YhRE4bCUVYklk4SYkQ2bR+hKU+RvvCdKmabLUgkR0YcNAT+SL1mgC8MHG9FqbUMf+SpCpmz80WjuPcdqIivlJ9pmas4M+4nKLlVG9jU+0Q==,iv:sozsAaj3GoNPUmNJLkDzV/X7/gWBUn97YYSJuGPvhnA=,tag:zvMqWhdkB0kjvLiPdmYLUA==,type:comment]
    #ENC[AES256_GCM,data:73yXi3ibrqmQxXiRJlyf5Ik=,iv:71Ho6ohgSwxfpqq0SHwab5pe28oovCw0m+2T4+zDI+M=,tag:h1CJqybQiWtskSxpNTpRoA==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:4ys4g5nP,iv:bsZePES/L7+AoBXtuwz2PWW7rWeofygEEhyXKTTJRdk=,tag:4XNP+V86wF0EFJlpg86npg==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:C0mOx6K8fMLU,iv:g4PDU0mgxkPRfReM34J31HaEmLXH6iFEO8KgKfWGSNU=,tag:/nmvdBoO/LjvY6Epa9XEew==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:aKiHFz9xHL2PwAXJihq1PsE=,iv:mxiBuljqAO4dxL2mW3ID7fk53Em32rhPMdgdAnObhOs=,tag:cmW5o46ipv0PkTRS3xrv2w==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:77oddQgCB6zqFuuYEKRgLfmTs207d+gxfrASJf4ClVVA8nzR4SuxpkfHcUY=,iv:XddykaJxHiSK8xGB1p2YwqXNOUEMAY/YmQPS0GGZE+k=,tag:mdyEdhGGR9+WJDY8W4Y4Fg==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:qF0GePqnHQKAPxO7rvtENfeRNDTNP1kKIZEJusHb4Cb5/b1x2aUbf3b2Y20=,iv:Q/vY6h6O0Xxu1EshFcAdp2yoiVGiex5Lv84S+TZQbVU=,tag:ZeG6eQbOHQbQmPG3EelQog==,type:str]
    #ENC[AES256_GCM,data:aRlhmHODPjjB9Sw9+S4cluoNEtOJ2aNs2Pdv8abAj3mqzXcggsw2dH4ee4CNjoE5u6mcNKZ3JGf4/xmNhz/Uu8xZ6jy9BM179ZI=,iv:2yyTwkHN7ug0z2vIILNnE+I5ZPAGbKjMOnqDwhl+hw4=,tag:YKfw79/qUg4jjOXmrWtUdA==,type:comment]
    #ENC[AES256_GCM,data:xRGCpfFU4qz6GGJxQN1LEqQ8Y+p0M80obor9YFm1Yje94/Q8xvjGFXFChxS2Q3gtqJ6HbA==,iv:aOpOqwTPGotGOwOzTQ3AXGcSpE7sfIHhu7QH8uuiCyM=,tag:n3ozhtKPzLHxQEAAQ3xmrA==,type:comment]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:ntKZ1/Mr7tShoHBC3w==,iv:yOL0Kq87pf1YXgkpTca+7zTNZ0yDfeNBbO7+Ye6MKk8=,tag:eKPpEe+Pdeh58duC03FJbQ==,type:str]
    FIREWALL_INPUT_PORTS: ENC[AES256_GCM,data:IbKr9bn/hnUtKQ==,iv:bSJY00XmKCQNaQWTwUrR1DCi8OHO+sABdTah56+a+yM=,tag:GR4W0/UwKp82b0D2LDzt9A==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:Kw6GI+GJh+8NbQ72ZwUlNaN/CKDDR7YWbdU5ZsQ=,iv:nRqzN9MfV7mWRLjQ1lRdh0rpwrWZAS5ZPZoO2PggTM4=,tag:+PuGjT0kflgN6glxRVpNyw==,type:str]
    DOT: ENC[AES256_GCM,data:n3g=,iv:Phzqi6JAUeL2f6kCmI8jqIEVz7zcVg6oHPcOghQpcuc=,tag:s5JU6/VR8CoFv0hTFBq7Lg==,type:str]
    DOT_PROVIDERS: ENC[AES256_GCM,data:y1Y9aBIDpwDMPA==,iv:Grd9tTeCYbonqIb9PI/Vyv8zmegYoHwqRRFc2ge745o=,tag:tgAKb2ZtjF/DFKefgZ0Ilw==,type:str]
    DNS_ADDRESS: ENC[AES256_GCM,data:yK1PjRzDpHNH,iv:up5jyKfgOlnRsxG7NYZ/KP9ZGHdCz3x1rppcQeW1yxE=,tag:H/YU74n9s9AX9MejUa5iGA==,type:str]
    HEALTH_TARGET_ADDRESS: ENC[AES256_GCM,data:o8muTag8TZTdV4P/JZ7zb5Xm,iv:kSPphEgVtOAzbRIEvBHZtMIKmsyI0Punrotc7kBOuGQ=,tag:c6Ak4WtU1ld9gbyA+T6BRg==,type:str]
    TZ: ENC[AES256_GCM,data:P8PTDVi08/0Was7YunR9c07TnA==,iv:JJqFLXDc4PgnLUTOMWYcfpkseglxxR6x5Ah2ZMFTQQQ=,tag:c9OQwRorm8FCKZ0/9N9K5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N2RtOWZ3d3VQRVhGRUZt
            aHRVRFFhZHZ3REhpZ0NUQUhXMWIyZWlSSFJZCm9aUHFqNkhRY3Y1aHlJNUFKTjJB
            UmhzWmNSZW5oZEFqK2V3d0E0S2dRa0EKLS0tIEdGNE44YnhXMTEzQ1RTb1hLUXdH
            RXlZYlg3WTZwQzZmY3JFMTRTN29QYmMKq/6g7PemM8vW9N3QabTtFs9k+ANlL9ab
            q6Bxc/jFyQbqDToHu+Up6oCzRbPe92n7GRAvIRStXahMUIGBI0+j2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T04:09:08Z"
    mac: ENC[AES256_GCM,data:gekZkBLPdZc2liPdnbOyi+EY030G7T40+2PZvxM3xhF5ep/syDOECQwGOj8mZN9khPbvTQtjMVBeGlJItoa71aKZ93upn4eG2Y4sT7gJFtazKLwUQXLt9E5yDasnLXrDp0RJHyRe0GtVStgcU2xqecZfwMsX/18hiYhD+mQYlQU=,iv:ddgRa7mkPg+ivqsZcRDZAwVigwaBEh0KwBHjIWqFOgI=,tag:GnfTq7cx1JgsjnsqNPjvdw==,type:str]
    version: 3.13.1
