apiVersion: v1
kind: Secret
metadata:
    name: deluge-vpn-env
    namespace: media
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:2jxfzwQC47xB9AoEK1gur12m5m/3seWEEDcSHSyNg5RSdJIam23tzBTSaqA=,iv:692mc6/eA2imUlRMOj//Gz8gH2v0i3n/ELJzKPhxr/Y=,tag:K3bcR8iNjw3JtYUl7pOSfA==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:OY9MpoM6QBckcclFqYjphpJ0qYRyTJVjdJCp1NzYrXTopRjnzLqD/G15Crw=,iv:pp/gogTgc4N2YYYUgPxcFWcAGd0DZzz5p0ecZOHGZOk=,tag:SNXj9p7a4xOrj6FnV3ycTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNzR4ZFR3a2I2TTZZUmtS
            OVQ3anZPWEZNZldpc0F4N1ZmQzFlRXVPU1JJCm5URldQczZVdDUrajRyak04d3V2
            SmI1SmRyaHQ1Qmg1NkNtUG50Tlo4K0EKLS0tIDQ5eC9uS3VOaFhFTDU3c2ZzazV4
            bHI4b3ZNeFFqMll0dktoTjAyRjUxN1kKXY2+j+cfQtLhUsQHHy2q6C6XsYNoQcAW
            udG1EXkQ95K0GAgDwk30z7VN13yBtOtkS5KWUVSdYLKl6iXtnRDEqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T04:00:27Z"
    mac: ENC[AES256_GCM,data:w6dunZuUtJCyJ7R1ibTE8G0ypehUcoaDHZfGOaKugYuewn9KIxG84nnMsU7GomsJgau8ylSwhmcZ4t4MIkRlFCYEjjrCtWU5Mgml9Bo9XLm4rKMYxXwy7zp9vXMWcmnmH95mmdtpn/WLATp1GJe5TDnT71PZ5mZnOxAflKKfJa8=,iv:IPibblP4dFNVa7/7BnaBSQNBFIPFFfaY7g1Pwd6Ihzk=,tag:+ZS2mAVHhHhWVhWcijYDYw==,type:str]
    version: 3.13.1
