apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <app-name>-pvc
  namespace: <namespace>
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      # If your cluster uses the NFS provisioner defined in this repo, explicitly
      # set storageClassName: nfs-provisioner
      # storageClassName: nfs-provisioner
