apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    app.kubernetes.io/part-of: gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    app.kubernetes.io/part-of: gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/part-of: gitops 