apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: web-shell
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps/web-shell"
  prune: true
  dependsOn:
    - name: traefik
    - name: cert-manager-config
