apiVersion: v1
kind: Secret
metadata:
    name: paperclip-github-app
    namespace: paperclip
    labels:
        app.kubernetes.io/part-of: gitops
type: Opaque
stringData:
    #ENC[AES256_GCM,data:HOEV28EuaI7J/9fWBPKw5TSoDRrOerUrdD1RP4IMU7Jf+BeTfyBm3O7jSzQpEz3Qbd84nbaCJQ==,iv:+3UNF77SXewnLNYEuhauk90/ChUnaAcCLlJTwGlVkEs=,tag:SwgBfPRTPjEnkHdphN7Xpg==,type:comment]
    #ENC[AES256_GCM,data:JKJONL2Tib5zP+aIcZ4uROTD+TZolPcEX4XRiWSJb6ixHfFAvvA5JH9dmIbHWT5i1WUf6ngIH6GJ3zgrogu0e5iuP+uc,iv:TE9fxc4ChfG7GEV8Bw2KVIAphjiZ+ygQYbH3wFUnbzU=,tag:mf5zm/jZjXNLI0QsR0fSqg==,type:comment]
    #ENC[AES256_GCM,data:R1YxhgHGnSFIrK2kuoaV6rELEyrJJwLnxg9XlzW8J0hkUQIGgLieQxaWPLgPEyAJVUyzcOJiXujUIPIZDvqujVzPqM9tsDIfUm8QXzs8BZQUZp4CPdHzl0up,iv:yuJarGl6mnysJQxyMIK2SMUq/5iyzYPuYIQk58IV7Rg=,tag:tmV5DBKwbfmxuWRAyq/iPw==,type:comment]
    GITHUB_APP_ID: ENC[AES256_GCM,data:8Vt496fpZdK2sdGjZczAxdobhA==,iv:3MB1QHniqvuo4Enp95kkp74vJfslJsbZE+eoQQeY9CU=,tag:QI+d7nsrJ0OCVDoGxwkb9w==,type:str]
    #ENC[AES256_GCM,data:Hi+C301Oo0kejkgJrIjE/MFtvIn7Y1B7na5qanPntEX6TiK0FURfM4jdYfhPQrnI2W8FZ6FgalJtynZ9xsPDjx0I8j0rQDAJsXR8fw==,iv:4IrO9nAWLo6nFRs4TR41lQwg9YVOtow0JHAG1uFWdqI=,tag:EEilSJxcNgcLbiFFj3TVLQ==,type:comment]
    #ENC[AES256_GCM,data:dBmm1jY1PTJDceFZk9bbXZ3MOc3Yf9GqE9CNjfA/xt4JZ07UZjM4wcO74tu8/hRbX4R9UDG/7yefqdcQn0L1lPQ/lD1L1ACIozwGjcQ=,iv:vg7bFC2Q5NDIfvDNlU3LqRXZQHqr+x/vF/65k+gVcU4=,tag:cvFzJD6agaxU5+8HfjDKSQ==,type:comment]
    #ENC[AES256_GCM,data:SQO/s+mA0qPDUOajhuJjlHAbYhVevv9QiKIuOwVTNK4Qc8am1v0Sm5wE1YnJ0S6l4w==,iv:zeU5SKdDzQdYzOqnjJEn+iTdI6PzaMXfIosx/0e4GFE=,tag:QSqiUerKs/mqvxKkuVWGeQ==,type:comment]
    GITHUB_APP_INSTALLATION_ID: ENC[AES256_GCM,data:6x5Cioca3UxQWEANC0s3VoLYKum3wH+1Jm8tZg==,iv:ac5N8GWEMoVQt1Ir6JTusJvOu153/h/XDrAmt7sOD6E=,tag:l0vFnO2ZF03Xl2BYIqbYTg==,type:str]
    GITHUB_APP_PRIVATE_KEY: ENC[AES256_GCM,data:S+ZtBOFCenMMxyQABc3gBpNFSu60oYg0KG9x7CXBbF6ZXyAe+xu9YWvLR+8ThIVPioiCpnSqmZpt9c/6q+p+hfeo96TlMdFk03pX74ClKVNpUOK0CScRTA==,iv:ZJ4pmh7yGll4jB3/A9Qh/ycUeLGGfFWXhzI6esP1NM8=,tag:Vawrncn6KCVNSHvmY72Tfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZVlicHI3em9sS2pla1J2
            ellvQzRSbWQxQkkvQ2R6ZVlWZjBlZEQrVGtRCmdHR3BsTWhiRS9pRnBmY2Q1L2M3
            ZGs1SWN5MW1BenBRVExpdll4NStidWMKLS0tIDVhMFM5bzhkVVFYd1RCMWswTUZL
            MDBBTTVNWTlHaEswZDVLMVZQVlNMUWsK/JO8o57hH8PSZ4NiiAD52BkFoUswzSgh
            X7+80lLsyaCQ+OvTutqZc45p8PHmlphPkMgyRucoW7RH+hJWS66E7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T17:43:26Z"
    mac: ENC[AES256_GCM,data:BBCkndJw7DX5acoQpXeug5GHvqHAc98aMBtq5Z9IStkygUVIsD2XIDH/bul2jUj1ZOfwyT3/ngDoUHnXSf+USVxE5nUh4iCtPZfqwZ+Z2dcqLIQt36wEUag+Nt2idOgH/wFJ89viQ3KI4SekFIP8yQ++gmZ62aLVL3p5JnTd2gw=,iv:Mw1Yq1MjLeO9CnK6wLLtcq5eCsDHE35j1cnGAfH7wkI=,tag:E09suSL4xuuy9y7GQi9u9g==,type:str]
    version: 3.13.3
