apiVersion: v1
kind: Secret
metadata:
    name: paperclip-secrets
    namespace: paperclip
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:GhTMEJ2SHTp/D8X3nxpNbQ3hQr1WPXWWNtPBe5LwvYmCl9UGU3LsSxX6ab1L8SOF9/qRgs/oXC8aFcFulA7c5wmr5e1fd+2dKIhfUwRQ6DXecdyubG1zbVuarUdEirqByV9+/KWJdUU+xYJhE6XhdRY1zEPkwpY65DhAuLa/yvQksrmjNQ==,iv:63J07DUIp4c2hCTPgJWLgz6D10HYRS6IfwW6EpyAiTQ=,tag:5vC6kkXCtNeGq99c/gyNxw==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:PUobXW2NjmLdN5QON1I1ZhM/xIoi7/1Ppxwa02aBcJfTkH++xAXFD9xCeLFcqR7zs4L0B8onyTojXSEISKKImw==,iv:0kqsmGk8TXJHDTQmcb0WMcO/V84imNpjcgofWpILzos=,tag:yelZafSIgYYVR5hcRvg2RA==,type:str]
    PAPERCLIP_TOOL_ACTION_SIGNING_SECRET: ENC[AES256_GCM,data:809MFZTUVWxCGrYLXbZsyXTzZc3yLerH7NW0gawhAKHep/UGlOUUyLz56lkD272QyMR/Yp4reeTAy+/NJjQ+Fg==,iv:hApnG/a67d5fAP66TfP2I+d14x2iUkfWc6GJR1a81g8=,tag:0eZOnSFEAwllE2Py3wvqBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTGs0a0MvNldjOFVxUmRW
            VUtKRzJmcjB2OExJTmRiM0dKbGI0S2ppODNnCjZ4Rk94Y25uN2FzNFJmTDd0NHVq
            MW00ZHAzV3JZMXhzckdkempQMmNReGsKLS0tIHpsMTViUEtYUk1yQ1IvT0FoMEtZ
            a1lKOU01UjRWekwwY2tqL2JyYVJIYm8KVo0K70f6d+FBQFAzBz4ZEwsOMleYiRKq
            Y1wxjs3lmMPX5cuebx+/Z7FwQ+dMreW2DOifYwlLw5IXstN4MlENEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T23:45:23Z"
    mac: ENC[AES256_GCM,data:6oC0uRzXwH2bHh/V+Ntt4fZq2bWqFNXoJjxs13bp1h4dlqfvAFkH8xAQcXa9oyEgTGf6UdwqHmXMTOJRH5XqN5VpEzEO5tq4aRVKB33bP67v6/oPnbgMAFP8/8RUVZkE7LoM6CfNNm4lbivVZP9tOezZXXncKGPPa9J46wBYQNY=,iv:5/6/aF5OJgEo8/mdcj7gAOJN4QjZGDle8xCi0nc3S4E=,tag:y3CdF91hYQTXE3AaFO5qww==,type:str]
    version: 3.13.3
