apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openhands
  namespace: openhands
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`openhands.dcxxiv.com`)
      middlewares:
        - name: authentik
      services:
        - name: openhands
          port: 3000

  tls:
    secretName: openhands-tls