apiVersion: v1
kind: Secret
metadata:
    name: openhands-env
    namespace: openhands
type: Opaque
stringData:
    #ENC[AES256_GCM,data:HeN4dKNQBexw5IU3I639Q6FAlxiWrSNPsDq0wTEiBPQseXN7M8QhJSIraxoEjLKkcy+tWD4fzICveme1CDjkEwDFkQ==,iv:Rd1GAMcdblCYrvGpWa3IkF+VVExVxfTK5VJ0KNNk6oc=,tag:d8PYkDTMBePOo5yV7xLPxw==,type:comment]
    LLM_API_KEY: ENC[AES256_GCM,data:jsPOXALpVHRqa2SEj2TvztJAbKkZrPg0B9rT1jETDO77Li0HVG6cD8aaZ3DCaLdiWfTB4zIZ33xEFlFo3drzvT4z+AbZSNjt8IKXGIjhoO3I5tq0+6vTLVO8ixbidRK3MeP/hp+ZadnO92Ql,iv:HdtGfNvI6s1dibFxbC7IstzLo/JzL+FlQOxY+U+Q40g=,tag:7GTOy8ZQYVrd1/AGitSPeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUczN2MHlSZEdpZWNwc0VO
            WGdRYXdhNHVGU2dwUFJzcHdQbVg2Z1JWN2k4CkFDbWE5a2NDWk1yREdCV3UzNEhY
            dERaV0xlNWtCTk0ycDU1cUJtV0R4R1kKLS0tIFFqaXdhUzcxd2xEZE1TVmY2bmND
            dUxGS3Y3Y3ZGbjlQNWpOUDYrU2cvMFkKWdbRS6vVqdw7KXIrOcDApn4s2NKxDQeb
            TG9vmKwnGy2sC0n/+7WNCl7GlIKtJluKZekrw+Ga6dY+PgYzXLV/rA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T02:07:26Z"
    mac: ENC[AES256_GCM,data:1D51lYdEchjatccPCIl58eDrBOlirwuZgzb1pV9guDEB5Ksqa4Def2yzdYFFMQ2kQIMwD84LF62Cy2QeVlfPbDv7waWj2tZd5WaZU9lpkTHiqiLEGI1bC7Q2p2uZO68qghlPtrmbtM6cii4nxUfP5CqqOrOsCevhR90CVzr8JAU=,iv:OZSVnYdT0w6dP9Ovad75OsiTCSHEyRVLRMnMsp5as5A=,tag:R+x9/6zJpKili87VKCOyNQ==,type:str]
    version: 3.13.1
