apiVersion: v1
kind: Secret
metadata:
    name: openhands-env
    namespace: openhands
type: Opaque
stringData:
    #ENC[AES256_GCM,data:HeN4dKNQBexw5IU3I639Q6FAlxiWrSNPsDq0wTEiBPQseXN7M8QhJSIraxoEjLKkcy+tWD4fzICveme1CDjkEwDFkQ==,iv:Rd1GAMcdblCYrvGpWa3IkF+VVExVxfTK5VJ0KNNk6oc=,tag:d8PYkDTMBePOo5yV7xLPxw==,type:comment]
    LLM_API_KEY: ENC[AES256_GCM,data:3+c8aKhatNdB7ZDMjM57b6WIkHIvFP88VeeWj5j11UEja9Zn,iv:kbNZv3YWsRqBGsfz+wNMLTme2enR60MDKY1lUKb18PQ=,tag:19sGfeD0lGg6XaojgvEjfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUczN2MHlSZEdpZWNwc0VO
            WGdRYXdhNHVGU2dwUFJzcHdQbVg2Z1JWN2k4CkFDbWE5a2NDWk1yREdCV3UzNEhY
            dERaV0xlNWtCTk0ycDU1cUJtV0R4R1kKLS0tIFFqaXdhUzcxd2xEZE1TVmY2bmND
            dUxGS3Y3Y3ZGbjlQNWpOUDYrU2cvMFkKWdbRS6vVqdw7KXIrOcDApn4s2NKxDQeb
            TG9vmKwnGy2sC0n/+7WNCl7GlIKtJluKZekrw+Ga6dY+PgYzXLV/rA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T23:34:32Z"
    mac: ENC[AES256_GCM,data:itE9RSYEDAngrV7T6UweDBeKa+Rv/iJ/TSzp6jdRzGSUFQUQ7dLDEuPxeVbsVhVX3X8vFslTAT38aa/fF7IshmdtVpWkoSzJDg1EEWADjACoew04SmsB4JMkxldxe0VZRjE+JaqCFsBL35xyXp7PGCkTYVAKvojkifgrhW1Wrx0=,iv:TUvlVD+NGdqdhaU6NYKbr2lr0LntVfA4oLGOOQYxM6Q=,tag:wD23YYGl9gF67nttAy9vYA==,type:str]
    version: 3.13.1
