apiVersion: v1
kind: Secret
metadata:
    name: juicefs-redis-auth
    namespace: kube-system
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:rnE1e/EkBVYSant+FFGr/EW1iMraRx6XhwUjg0HE18Q/iaviPocRBg==,iv:Ak1vr7QJI9TrrlJR/8RobF398ZZcx0S/JFh2AHNOw98=,tag:6oo8DmAoy0RMj8zeUHxS3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL0RIdE9HQ1hoZElwK2JN
            YjZ5NXR6TEFub290dGpPdVV6RVdVTW9FdXlBCldZUWdYTFBzTS9jeG56ay9CdU5m
            MW4yeUJ6OXhUeHZzcDJvMTN3bEtaYjQKLS0tIHFldmloNDVmUEM0UzYvamF0S2ZX
            Q1VVbW1vZXJUUHljaW5iNGZGZmllcWsKqk2KKxZHzGMvm1X61RA8GuSHW/TElNBF
            m3twuIdPj6/50BtoFTlUrcpXbCw+vrNO+CTTem35IUAGKYWnBZgV2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T17:20:32Z"
    mac: ENC[AES256_GCM,data:2T7g8a1G9H/l/Y3tsuhsZ63WFZV8Op1uX8GcCwVB3GjPfwPBb7xnVoVgS114wjGjORxxcLn4hj7dY+OGOHQaQpp0m8j87saHqrBtvcjOoYos0JO384pxpjqGRMk0tetyO+XoFoNCdGZyEdeqIHzhASJMEnfJ2T7y0K34ah5iqh0=,iv:SsqNl+cYI8BKNuGYvKDPqcUJ8wbqsqTPRp1WLYrrv7g=,tag:aEegX8VQxRTuG24+LQDUdw==,type:str]
    version: 3.13.1
