apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: wordpress
type: Opaque
stringData:
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:tV3EC9ksXoHMsFpfrnUtQFEN4OShOuh0J5YJhQ==,iv:5IyF4MNOFmf+oahzp7VA1NfHeCS4flg7RjZEJZfvz+s=,tag:Drdu7A024KaQspM696qtBQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:huQbEbUV+z24ULMbbBUrMD40bBFJ0u3AkQe2Pg==,iv:w1SFnlkwDBXQ03PkJkPgR8qDCIQ4wyvTGgOtYpG30Ms=,tag:iUxlh/hA6dfZxnTJz4ejzw==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:aaD/1vzlcxmUQUd7AR0ZU+8QZm3k/XagSFZThQ==,iv:AHFpSgDc9EtqEBsb4Si0JDkvpN8Pteji9RDmPFNpSO4=,tag:wTFkCzLYqn89P3Kc/aIkPQ==,type:str]
    WP_ADMIN_PASSWORD: ENC[AES256_GCM,data:5tsC4W5TNysEipKAYHaEhxS1lHst+Vyf,iv:bv29KuqkcpwRLaPlVlgC9jUSVYpRO0nYy7d3wi62/0c=,tag:PIA0O1yzPsvIVQMWXIkVmw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:u1/MiU+CenTOGCL60ttXeNFpBNF9woC8,iv:k/1hiYkuB5Y8ePHS6DJdxh8qNkJ2pgSC428b6z0ujvs=,tag:n47X6PzNEG8LMUWjHReAsg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:G1inOwnKEBJ+lO4cI8JIF6PdmpvV05BtSF8PcJGiLauaqTnLo30skUfokge9zUIwyZU=,iv:3072ZJBZN0tdNZGcTxUB6ctDZWkSXxC03OnI3xY73bc=,tag:tdErYk3n8fXrB2FkmDeiog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd081SUdYYU1iSGlTZXFy
            RVdGeE5LTnl6a3hSWjBwakNXOStIektNYkMwCmxUakRZL1JzUEgrWDNCUUUyNHlU
            bGtHU2g1TVV3THJGMzlUTUZwNHVPVEkKLS0tIE1pSmIyT2RYaU0veUxINkdoUU90
            YTFBQlM2aXhYdThMN3h1YkgwTUM0Vm8KdnZUN2myoTPl2yIBWhR/ooOijklFZ+IT
            xS1mQS+o7K7DxGkYilOCrocEcW1Wnle/OtSpurMln3dzeJIXLd4ntw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T22:48:09Z"
    mac: ENC[AES256_GCM,data:n9zS3yVJxszE9Bqkud90djeAKmuJkrDoveh9aKKoF54qvK6sdIrkeyA14e/zdZalZetr7P50Ipxy83QJgWt0VwCgHqlkflbjrUgpNVtZS/01dXvF/uXbpmUDI3Ya70uy8LfTIcueKstO8SWlMMKGQSuicuZzj2KCFwl6mTwWTJQ=,iv:SGm8wUDtMnrq56vzIhgIA2dZTPw8MjI5VdfCaSWJ7xw=,tag:TGEirMOMP1sTysPEiKgUNQ==,type:str]
    version: 3.13.1
