apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: wordpress
type: Opaque
stringData:
    #ENC[AES256_GCM,data:IV5eyh+av7eDQi3I6LqnUO9laGASs95oQbyesscUjaXYdBbnPBxACjIp7rg17MJgBXmTRytwbCDicoxH1myrO2cYBIjN+i/GxyM7dwqPWg==,iv:7QkU6s9kaft6jhF3lPtqvByGoFhV0tlwGsZ3vP04L1A=,tag:nwnFqALlODdJTu+b3SIgwg==,type:comment]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:7jlejr7erhvvy3VVJoWWCavE5Bnrqke72uk4xH5AA5UherRhQrcz1Q==,iv:i9gOhVVX50YiWO166n9h5gcVfbog9GHVcCRcro5DKfg=,tag:6xh5kT6cV6yiJwekKyUing==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:AB7JsPsWLEuEvhqdN2MwLR9WCiW2p8Z8+JVnYkRpvQz5VrNdVjxPDA==,iv:8b0IfWEO4PalNQYh3o+f9Tfp+m6IwEfeMp/Q3QIM0Ns=,tag:6Exqz1YB5pA1f+EuApGb6g==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:em2ynig4Z122CnwQi17Gl+bP2wwVkGwVfdOjGeN0MYKSIKiKwYwPyZg8aTkDLuwQ,iv:Pu0zUu1UGpwGWsr7jzhfRNfzRyjVniKLIwnwibqoBgo=,tag:kc62NbhQi93mtiu2h4JqMw==,type:str]
    WP_ADMIN_PASSWORD: ENC[AES256_GCM,data:c4NOGD89taAlfeVwLJiJ+2qY4SVwkMTm,iv:Wb+9Bppx4earRJJdmgwh7SSvUdvWq2E9cLptenMG2Y4=,tag:Z7CjQthDPeBl5X4t+t9nvw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:6+i/f0+bJ6c9TXLcWgCL0+2c8ijncFxO,iv:hWMCbNPzPhdWRL5ZJjUa7hZ51mVjB70aeWPMCIJ2w24=,tag:XQ5lj/V6YfjJu+sWqquQ0w==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:it6kZmg8eLSPFrKcvbayWS1CgFAW5oAgPv1CbPOJQYI1lN/f7B7L0Vs6Npd6b9rW0fA=,iv:UwfPI330IKyg4kJeg99JmEKVmv+iGWTOX43dpnXAWJU=,tag:7x4E4cporrfTozaAImlgIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbnBUN08xUUNqWCtZM2tK
            eVJxUkxpU0RmeG0wN0hsVThVOUJ4dElXeTAwCnA1OXFMRENJWE94c0hGTFFzR0FI
            Q3BFVTZTZkIvZHFhVHd5QzZ0bmdBdzgKLS0tIHZBY1FoNHVFNnd5ZURYeXF0TTg0
            UTdqdXk3SmZVOXV1R29LK0s0aFlGcFUKmbWinT0GceagtJ3riuVyP5xjSfy7snFx
            /eWMs4ghOD/cMA2TYn3zqBLCbleEDwHAOjB6fx4Oed0Rqrh29hoORQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T00:09:38Z"
    mac: ENC[AES256_GCM,data:PGH/UI9RbvjzX0P1mqqsJ1Rf7VP4Az+7ekS0BmnKxTxIzw5G09eo7cPnPPr/5Mzwhp6VnANE9xJTjl/Oi8AsDaAO9as6AbyTZuIm6uoD/5/js+vph9oa2qE2MgjkpAmY/fY2jihyGFI0FxPygGUSAXafB7+5Jlz7BniWngwDMIs=,iv:JBViby4Y/4CQM3PDY6ffx8zb/QaY03PV4PDYrQvOBto=,tag:S7Th94A3NmsrkYIcAy4LQw==,type:str]
    version: 3.13.1
