apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: wordpress
type: Opaque
stringData:
    #ENC[AES256_GCM,data:IV5eyh+av7eDQi3I6LqnUO9laGASs95oQbyesscUjaXYdBbnPBxACjIp7rg17MJgBXmTRytwbCDicoxH1myrO2cYBIjN+i/GxyM7dwqPWg==,iv:7QkU6s9kaft6jhF3lPtqvByGoFhV0tlwGsZ3vP04L1A=,tag:nwnFqALlODdJTu+b3SIgwg==,type:comment]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:YkXsDFLlFEiDHnlICjuZNW05zQuo9SVB1f1LPg4YvA==,iv:WAYGisocM7Fq7Q20VVau3KwGFJVNJiIMAtekIdkoYo8=,tag:64y+/hL1Cq+v6V005YSZ0A==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:tB+PPDoWVs35K00ADYmtsqAXstRBQrs5eNeDsjKvsg==,iv:uEsnJjapyig10R7JAQeWhSoha8Ht7lmdWu+AZur+54c=,tag:Uhnk+exbTHG/cCqp6B/3Vw==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:aoEMygysGQ3dHUGLYkLPdY8KLoje36bPCV0+5yGHyA==,iv:tewzYg4pPaNsdsSSGQT7w+B+OFn702TtznKP4QdtEMY=,tag:30l/3zrCHanmD1X+pmQlpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbnBUN08xUUNqWCtZM2tK
            eVJxUkxpU0RmeG0wN0hsVThVOUJ4dElXeTAwCnA1OXFMRENJWE94c0hGTFFzR0FI
            Q3BFVTZTZkIvZHFhVHd5QzZ0bmdBdzgKLS0tIHZBY1FoNHVFNnd5ZURYeXF0TTg0
            UTdqdXk3SmZVOXV1R29LK0s0aFlGcFUKmbWinT0GceagtJ3riuVyP5xjSfy7snFx
            /eWMs4ghOD/cMA2TYn3zqBLCbleEDwHAOjB6fx4Oed0Rqrh29hoORQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12fnp5hs8jywqvcd6u8tzne8np64h2xucqlfr98gj8r0lw5zmjeyqqw8dhg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T04:06:59Z"
    mac: ENC[AES256_GCM,data:p4AwP5vOICIuC+eg4Y589lMCMr/T7cK2CGL+hPtwgy6OayWvPmSAy4bW1lL+2qemTGY4Y4c+tpGIFjmL/ykd30CnwR1BEvXxaj+MY2D2qCs9c35MvKDPDvk5br+hDmsEahREzSKi4QHCJXzZ948Aa0gCkAHqeF3L8RFmQgn0ntg=,iv:2eA/z5ygCNpfERMqTyuHDU9eTKHDG6oiQN4eD4eSSFg=,tag:MNP1DTSMsHtyr1mVtQMl4A==,type:str]
    version: 3.13.1
